wxGUI/mapwin: add map overlays 'at' parameter arg validation
OSGeo/grass pull request #1069
Opened 2020-11-05 10:42 UTC by tmszi

**To Reproduce:**

Steps to reproduce the behavior:

1. Launch wxGUI `g.gui`
2. Display elevation raster map
3. Add elevation raster map legend
4. On the Map display window double click on the added elevation raster map legend
5. On the d.legend dialog go to Optional tab (page)
6. Set 'at' parameter argument (which required four number at=bottom,top,left,right) but set only one number e.g. 5
7. Hit Apply or OK button

**Error message:**

```
ERROR: Failed to run command 'd.legend raster=elevation at=5'. Details:

       ERROR: Option <at> must be provided in multiples of 4
       You provided 1 item(s): 5
Traceback (most recent call last):
  File "/usr/lib64/grass79/gui/wxpython/core/gthread.py", line 137, in OnDone
    event.ondone(event)
  File "/usr/lib64/grass79/gui/wxpython/core/render.py", line 483, in OnRenderDone
    self.updateProgress.emit(env=event.userdata['env'], layer=self.layer)
  File "/usr/lib64/grass79/etc/python/grass/pydispatch/signal.py", line 230, in emit
    dispatcher.send(signal=self, *args, **kwargs)
  File "/usr/lib64/grass79/etc/python/grass/pydispatch/dispatcher.py", line 350, in send
    **named
  File "/usr/lib64/grass79/etc/python/grass/pydispatch/robustapply.py", line 60, in robustApply
    return receiver(*arguments, **named)
  File "/usr/lib64/grass79/gui/wxpython/core/render.py", line 774, in ReportProgress
    self.renderDone.emit(env=env)
  File "/usr/lib64/grass79/etc/python/grass/pydispatch/signal.py", line 230, in emit
    dispatcher.send(signal=self, *args, **kwargs)
  File "/usr/lib64/grass79/etc/python/grass/pydispatch/dispatcher.py", line 350, in send
    **named
  File "/usr/lib64/grass79/etc/python/grass/pydispatch/robustapply.py", line 60, in robustApply
    return receiver(*arguments, **named)
  File "/usr/lib64/grass79/gui/wxpython/mapwin/buffered.py", line 967, in _updateMFinished
    coords=self.overlays[id].coords)
  File "/usr/lib64/grass79/gui/wxpython/mapwin/decorations.py", line 105, in GetCoords
    (self._renderer.width, self._renderer.height))
  File "/usr/lib64/grass79/gui/wxpython/mapwin/decorations.py", line 304, in GetPlacement
    '=')[1].split(',')]  # pylint: disable-msg=W0612
ValueError: not enough values to unpack (expected 4, got 1)
```
**Expected behavior:**

![wxgui_mapwin_overlays_at_param_arg_validation_exp](https://user-images.githubusercontent.com/50632337/98230450-6f9d5900-1f5b-11eb-992e-713cd487dc5e.png)

2020-11-30 03:26 UTC, petrasovaa requested changes
This solution is very specific to d.legend (and some other d.* modules), I would rather go with the system of validators used in forms.py, that is already in place, see for example CoordinatesValidator as the closest example. The disadvantage is that with the current validators in forms you don't get any information what is wrong and I don't think it prevents you from trying to run the module. The widget background turns grey, that's all it does.

However, I would rather improve the system of validators in general than going with this too specialized solution. For this PR I would try to create a new validator (maybe generalize the coordinates validator, based on option's 'key_desc'). For future I would like to see better reporting of the problems, e.g. through an InfoBar in each module frame. The validator could call a callback with the message and the module form would show the infobar.

2021-01-09 06:15 UTC, tmszi commented
Fixed in the [cac364b](https://github.com/OSGeo/grass/commit/cac364b154ba318d929e978867c211cf8c93a050).

2021-01-09 19:46 UTC, petrasovaa approved these changes

2021-01-09 19:46 UTC, petrasovaa commented
It didn't work for me, so I made some changes, see the commit message. If this works for you, feel free to merge it.

2021-01-09 20:08 UTC, tmszi commented
> It didn't work for me, so I made some changes, see the commit message. If this works for you, feel free to merge it.

Yes it work I tested many time before I send my commits.

According wxPython doc Validate method has parent arg https://wxpython.org/Phoenix/docs/html/wx.Validator.html, this [line](https://github.com/OSGeo/grass/pull/1069/commits/fc2be51d6ccce25f5a10d85ae76444beec9cebf3#diff-8e8cfba1234fa3d8cb36e4bd2ae0601603d5739c68709fd2a62494d7dc827d08R1062) is no needed.

2021-01-10 03:03 UTC, petrasovaa commented
> > It didn't work for me, so I made some changes, see the commit message. If this works for you, feel free to merge it.
> 
> Yes it work I tested many time before I send my commits.
> 
> According wxPython doc Validate method has parent arg https://wxpython.org/Phoenix/docs/html/wx.Validator.html, this [line](https://github.com/OSGeo/grass/pull/1069/commits/fc2be51d6ccce25f5a10d85ae76444beec9cebf3#diff-8e8cfba1234fa3d8cb36e4bd2ae0601603d5739c68709fd2a62494d7dc827d08R1062) is no needed.

Weird, this is what I was getting:
```
Traceback (most recent call last):
  File "/home/anna/dev/grass/grass/dist.x86_64-pc-linux-gnu/gui/wxpython/gui_core/widgets.py", line 586, in OnText
    self.Validate()
TypeError: Validate() missing 1 required positional argument: 'win'
```

Any idea what could be going on here?

2021-01-10 07:58 UTC, tmszi commented
> > > It didn't work for me, so I made some changes, see the commit message. If this works for you, feel free to merge it.
> > 
> > 
> > Yes it work I tested many time before I send my commits.
> > According wxPython doc Validate method has parent arg https://wxpython.org/Phoenix/docs/html/wx.Validator.html, this [line](https://github.com/OSGeo/grass/pull/1069/commits/fc2be51d6ccce25f5a10d85ae76444beec9cebf3#diff-8e8cfba1234fa3d8cb36e4bd2ae0601603d5739c68709fd2a62494d7dc827d08R1062) is no needed.
> 
> Weird, this is what I was getting:
> 
> ```
> Traceback (most recent call last):
>   File "/home/anna/dev/grass/grass/dist.x86_64-pc-linux-gnu/gui/wxpython/gui_core/widgets.py", line 586, in OnText
>     self.Validate()
> TypeError: Validate() missing 1 required positional argument: 'win'
> ```
> 
> Any idea what could be going on here?

Base class BaseValidator Validate method has missing parent (win) argument, commit [9515755](https://github.com/OSGeo/grass/pull/1069/commits/9515755ef7a42e15b26df8d94cc9cbb483387417).

2021-01-11 15:38 UTC, petrasovaa commented
> > Any idea what could be going on here?
> 
> Base class BaseValidator Validate method has missing parent (win) argument, commit [9515755](https://github.com/OSGeo/grass/pull/1069/commits/9515755ef7a42e15b26df8d94cc9cbb483387417).

I didn't test it but shouldn't the classes derived from BaseValidator be updated as well?

2021-01-11 17:40 UTC, tmszi commented
> > > Any idea what could be going on here?
> > 
> > 
> > Base class BaseValidator Validate method has missing parent (win) argument, commit [9515755](https://github.com/OSGeo/grass/pull/1069/commits/9515755ef7a42e15b26df8d94cc9cbb483387417).
> 
> I didn't test it but shouldn't the classes derived from BaseValidator be updated as well?

Yes of course you're right, I did it in the commit above.

2021-02-17 20:13 UTC, merged