ci: Update setting env vars, use 20.04, C gnu17
OSGeo/grass pull request #1092
Opened 2020-11-17 03:46 UTC by wenzeslaus

Update how env vars and path var are set in GitHub Actions after change in the API (fixes #1090).

Compile also on Ubuntu 20.04. Test on 20.04, but no longer on 16.04.

Use Ubuntu 20.04 for GCC to get the GNU 17 C standard.

2020-11-17 08:27 UTC, neteler commented
Thanks for the update!

2020-11-18 03:08 UTC, petrasovaa requested changes

2020-11-18 03:08 UTC, petrasovaa commented on .github/workflows/centos.yml
> +        echo "MAKEFLAGS=-j1" >> $GITHUB_ENV
uses 1 instead of nproc

2020-11-18 04:11 UTC, merged

2020-11-18 21:09 UTC, neteler commented
@wenzeslaus my backport attempt fails with an error, I'd like to leave backporting to you here...

2020-11-19 04:28 UTC, wenzeslaus commented
Yes, that's not possible. I did a separate set of updates as a PR #1098.