g.extension: for local urls do not do get_addons_paths
OSGeo/grass pull request #1105
Opened 2020-11-20 12:37 UTC by AnikaBettge

If many GRASS GIS addons are installed the following error message appears:
```
g.extension url=/src/grass_plugins/v.surf.mass extension=v.surf.mass
Starting GRASS GIS...
Creating new GRASS GIS location <tmploc>...
Cleaning up temporary files...
Executing <g.extension url=/src/grass_plugins/v.surf.mass extension=v.surf.mass> ...
ERROR: Download file from
       <https://api.github.com/repos/OSGeo/grass-addons/git/trees/master?recursive=1>,
       return status code HTTP Error 403: rate limit exceeded,
Execution of <g.extension url=/src/grass_plugins/v.surf.mass extension=v.surf.mass> finished.
Cleaning up temporary files...
```
To reduce this error not all installations of addons should use `get_addons_paths`. E.g. for locally stored addons this request to `https://api.github.com/repos/OSGeo/grass-addons/git/trees/master?recursive=1` does not have to be done.

2020-11-20 13:27 UTC, neteler commented on scripts/g.extension/g.extension.py
> +        # check if extension is from official github
```suggestion
        # query GitHub API only if extension will be downloaded from official GRASS GIS addon repository
```

2020-11-20 13:56 UTC, neteler commented
(this is a followup to #1009)

2020-11-20 14:16 UTC, tmszi requested changes
> (this is a followup to #1009)

2020-11-20 14:16 UTC, tmszi commented on scripts/g.extension/g.extension.py
> +        if original_url == '':
Yes, the condition is correct. Plus we need handle HTTPException inside `download_addons_paths_file()` function.

2020-11-20 14:21 UTC, tmszi commented
> (this is a followup to #1009)

Markus we need handle this 'special' HTTPException inside `download_addons_paths_file()` function, but I don't have permission to editing this source code here. Should I open a new PR?

2020-11-20 14:27 UTC, neteler commented
> > (this is a followup to #1009)
> 
> Markus we need handle this 'special' HTTPException inside `download_addons_paths_file()` function,

OK, I see.

> but I don't have permission to editing this source code here.

I'll suggest you on the PSC mailing list for full developer upgrade - but the procedure may take some days.

> Should I open a new PR?

Yes please. It may replace this one.

2020-11-20 15:30 UTC, tmszi commented
Thank @anikaweinmann very much for report and solve this issue. I opened new #1106  where I incorporated your changes and correct handling this exception.

2020-11-23 06:40 UTC, anikaweinmann commented
@tmszi thank you. I will close this PR.

2020-11-23 06:40 UTC, closed without merging