wxGUI/mapdisp: it is also possible to remove the MASK interactively
OSGeo/grass pull request #1176
Opened 2020-12-14 18:57 UTC by tmszi

It is also possible to remove the MASK interactively (left mouse click on the button MASK widget inside statusbar).

**Current behavior:**

![wxgui_mapdisp_mask_def](https://user-images.githubusercontent.com/50632337/102122388-b24d2d80-3e45-11eb-8a09-c5bba5e519aa.png)

**Suggested behavior:**

![wxgui_mapdisp_mask_exp](https://user-images.githubusercontent.com/50632337/102122399-b7aa7800-3e45-11eb-8fe5-54b8b3f0028e.png)

2021-08-28 03:04 UTC, petrasovaa reviewed
I am not completely sure if making it a button is super intuitive, but probably better than current situation. So I think it is fine, my concern is we may need to change this in the future to better work with single-window layout. But we don't have a clear plan on simplifying the statusbar yet, so this PR may be fine.
I would merge it though after branching GRASS 8 release branch.

2021-08-28 04:09 UTC, tmszi commented on gui/wxpython/mapdisp/statusbar.py
> +        self._mapframe = mapframe
Yes, it's there (in base class), I removed this redundant line.

2021-09-01 02:55 UTC, petrasovaa commented on gui/wxpython/mapdisp/statusbar.py
> +        self._mapframe = mapframe
You are still calling self._mapframe.OnRender...

2021-11-29 03:52 UTC, petrasovaa requested changes
Needs self._mapframe -> self.mapFrame

2021-11-30 16:04 UTC, tmszi commented
> Needs self._mapframe -> self.mapFrame

You are right. I've already fixed it.

2021-12-07 20:19 UTC, merged