i.in.spotvgt.py: fixed E722 do not use bare 'except' warning
OSGeo/grass pull request #1578
Opened 2021-05-15 21:23 UTC by ShubhamSwati

I have fixed the bare except warning in the file i.in.spotvgt.py

2021-05-17 07:40 UTC, lucadelu approved these changes

2021-05-30 09:11 UTC, ShubhamSwati commented
I made change in r.unpack.py to fix bare except warning, kindly review.

2021-05-30 09:14 UTC, ShubhamSwati commented
I made change in another file r.unpack.py to fix bare except warning, kindly review.

2021-06-13 02:10 UTC, wenzeslaus requested changes
This needs just a little cleanup, otherwise it is good to go.

2021-06-13 02:10 UTC, wenzeslaus commented on scripts/.flake8
> +
No need for an empty line. Kind of "removing entry, removing line" rule.

2021-06-13 02:10 UTC, wenzeslaus commented on scripts/.flake8
> +
Same as above. Extra line.

2021-06-13 02:10 UTC, wenzeslaus commented on scripts/i.in.spotvgt/i.in.spotvgt.py
> +    # code changed here, Exception included instead of bare except
No need for the text. This should be in the commit message. Extend PR description if needed. That's what we can use when writing the commit message when merging the PR.

2021-06-13 02:10 UTC, wenzeslaus commented on scripts/r.unpack/r.unpack.py
> +        data_names = [tarinfo.name for tarinfo in tar.getmembers() if "/" not in tarinfo.name]
Maybe a different black settings, but this line is too long and is thus not Black conformant. You can see it in the Black check. In any case, it is not really being modified by this PR, so even the white space should not change.

2021-06-13 02:10 UTC, wenzeslaus commented on scripts/r.unpack/r.unpack.py
> +        # code changed here, Exception included instead of bare except
Same as above. This info goes to commit messages, not code, but I appreciate the effort to comment on the code.

2022-02-20 20:41 UTC, ninsbl commented
Bumping up milestone as 8.0.1 is due in two days, while this has not been part of RC1 and there has not been activity for some time.

2023-03-17 13:12 UTC, wenzeslaus approved these changes

2023-03-17 13:16 UTC, wenzeslaus commented
I fixed the issues, so this can be merged.

2023-03-17 13:17 UTC, merged