WMS: replace broken URLs with alternative WMS
OSGeo/grass pull request #1635
Opened 2021-06-11 08:30 UTC by neteler

WMS URL updates:

- both NASA GIBS and irs.gis-lab.info are no longer reachable
- replaced with global WMS by terrestris and Sentinel-2 by EOX

TODO: it is not clear to me if the EOX tile service is supported at all.

Alternative suggestions are welcome, ideally WMS services with global coverage.

Note that the list shown in the GUI may be extended by the local list in `$HOME/.grass8/wxWS` if present (i.e., old WMS records to be removed there)

2021-06-14 20:02 UTC, veroandreo commented
The EOX does not work for me in NC location. I get errors like this one in the terminal:

```
Module run d.wms d.wms --q wms_version=1.1.1 driver=WMS_GRASS url=https://tiles.maps.eox.at/wms?service=wms&request=getcapabilities layers=bluemarble styles= format=png srs=4326 maxcols=500 maxrows=500 urlparams= method=cubicspline map=Blue marble background layer by EOX - 4326 ended with error

GRASS_INFO_ERROR(7364,1): Process ended with non-zero return code 1. See errors in the (error) output.
GRASS_INFO_END(7364,1)
ERROR 4: /home/veroandreo/grassdata/nc_basic_spm_grass7/PERMANENT/.tmp/localhost.localdomain/6703.4: No such file or directory
ERROR 4: /home/veroandreo/grassdata/nc_basic_spm_grass7/PERMANENT/.tmp/localhost.localdomain/6703.4: No such file or directory
``` 
Is this bc something is missing in my settings? In QGIS, EOX WMS service works fine though

2021-06-14 20:15 UTC, neteler commented
> The EOX does not work for me in NC location. I get errors like this one in the terminal:

Same here...

> ```
> Module run d.wms d.wms --q wms_version=1.1.1 driver=WMS_GRASS url=https://tiles.maps.eox.at/wms?service=wms&request=getcapabilities layers=bluemarble...
> ```

I suspect that `driver=WMS_GRASS` is the problem. I locally changed it in `gui/wxpython/web_services/widgets.py` to  `driver=WMS_GDAL` but then I get

```
Traceback (most recent call last):
  File "/home/mneteler/software/grass_master/dist.x86_64-pc-linux-gnu/etc/r.in.wms/wms_base.py", line 51, in __del__
    for temp_file in self.temp_files_to_cleanup:
AttributeError: 'WMSGdalDrv' object has no attribute 'temp_files_to_cleanup'
Traceback (most recent call last):
  File "/home/mneteler/software/grass_master/dist.x86_64-pc-linux-gnu/gui/scripts/d.wms", line 218, in <module>
    sys.exit(main())
  File "/home/mneteler/software/grass_master/dist.x86_64-pc-linux-gnu/gui/scripts/d.wms", line 208, in main
    wms = WMSGdalDrv()
TypeError: __init__() missing 1 required positional argument: 'createopt'
```

Improvements welcome (in a separate PR).

2021-06-18 09:15 UTC, tmszi commented
`r.in.wms` command:

```
GRASS test/PERMANENT:~ > r.in.wms url="https://tiles.maps.eox.at/wms?service=wms&request=getcapabilities/" output='costline' layers='coastline'
Downloading data from WMS server...
ERROR: Unable to fetch capabilities from
       <https://tiles.maps.eox.at/wms?service=wms&request=getcapabilities/&>.
       Reason: Method Not  Implemented
```

2021-06-21 21:42 UTC, neteler commented
Ok, so I'll remove the apparently unsupported tile server.

What else to add as WMS?

2021-06-22 04:24 UTC, lucadelu requested changes
The link is wrong, please try with the new link

2021-06-22 04:24 UTC, lucadelu commented on gui/wxpython/web_services/dialogs.py
> +                "https://tiles.maps.eox.at/wms?service=wms&request=getcapabilities",
```suggestion
                "https://tiles.maps.eox.at/wms",
```

2021-06-22 11:21 UTC, neteler commented
> The link is wrong, please try with the new link

Ah thanks. Slow but works for me now.

2021-06-22 11:24 UTC, merged

2021-06-22 11:40 UTC, neteler commented
Example Sentinel-2 - North Carolina sample dataset:

![image](https://user-images.githubusercontent.com/1295172/122918370-58cb3b80-d35f-11eb-8ba7-8388a08d890c.png)

2021-06-30 18:51 UTC, agiudiceandrea commented
@neteler I can connect without issue to http://gibs.earthdata.nasa.gov/wmts/epsg4326/best/wmts.cgi using GRASS 7.8.5 OSGeo4W on Windows 7.