g.html2man: IndexError has no lineno attribute
OSGeo/grass pull request #1640
Opened 2021-06-13 00:44 UTC by HuidaeCho

When the closing order of tags is incorrect (e.g., ``<div><pre></div></pre>``), I get this exception message:
```
Traceback (most recent call last):
  File "/home/user/usr/grass/grass/dist.x86_64-pc-linux-gnu/utils/g.html2man.py", line 39, in main
    p.feed(line)
  File "/usr/lib64/python3.7/html/parser.py", line 111, in feed
    self.goahead(0)
  File "/usr/lib64/python3.7/html/parser.py", line 173, in goahead
    k = self.parse_endtag(i)
  File "/usr/lib64/python3.7/html/parser.py", line 421, in parse_endtag
    self.handle_endtag(elem)
  File "/home/user/usr/grass/grass/dist.x86_64-pc-linux-gnu/utils/ghtml.py", line 304, in handle_endtag
    if self.pop() == tag:
  File "/home/user/usr/grass/grass/dist.x86_64-pc-linux-gnu/utils/ghtml.py", line 258, in pop
    self.excluded = self.excluded_stack.pop()
IndexError: pop from empty list

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/user/usr/grass/grass/dist.x86_64-pc-linux-gnu/utils/g.html2man.py", line 74, in <module>
    main()
  File "/home/user/usr/grass/grass/dist.x86_64-pc-linux-gnu/utils/g.html2man.py", line 43, in main
    % (infile, err.lineno, err.offset, err.msg)
AttributeError: 'IndexError' object has no attribute 'lineno'
make: *** [/home/user/usr/grass/grass/dist.x86_64-pc-linux-gnu/docs/man/man1/i.gabor.1] Error 1`
```
The first exception is an HTMLParseException, which tries to print `err.lineno`, `err.offset`, and `err.msg`, but it was caused by an IndexError, which doesn't populate these attributes. The second exception came from the missing attributes.

This PR checks the existence of error attributes before printing them. This is the new exception message:
```
/home/user/usr/grass/grass/dist.x86_64-pc-linux-gnu/docs/html/i.gabor.html:184:0: Error (IndexError('pop from empty list')): </div></pre>

make: *** [/home/user/usr/grass/grass/dist.x86_64-pc-linux-gnu/docs/man/man1/i.gabor.1] Error 1
```

2021-06-13 01:54 UTC, wenzeslaus requested changes
There is no more HTMLParseError in Python >=3.5. I think this is Exception in GRASS in Python 3 based on:

https://github.com/OSGeo/grass/blob/72fdbbb27831810a52326ab7e61a3aa700d1ebf0/utils/g.html2man/ghtml.py#L21

The part about script and non-strict parsing and removal of HTMLParseError from Python is not clear to me, but the exception in PR is raised from code in GRASS and happens to fall into HTMLParseError except just because how HTMLParseError is defined. It seems that a minimal change is removing the whole HTMLParseError piece from both files now when we are Python 3 only.

2021-06-13 14:29 UTC, HuidaeCho commented
Oh! I missed `HTMLParseError = Exception`. Interesting.. OK, for now, it's an exception, double or single, and I don't like my hot fix (ugly). I'm closing this PR and we'll revisit this issue later when we go fully Python 3.

2021-06-13 14:29 UTC, closed without merging

2021-06-13 18:36 UTC, wenzeslaus commented
> ...I don't like my hot fix...

My quick guess is that just removing all `HTMLParseError` code is the right solution.

> I'm closing this PR and we'll revisit this issue later when we go fully Python 3.

Anytime is fine I think. The master branch is Python 3. The Python 2 compatibility things were not removed, but it is not meant to work with Python 2 and it likely won't. As I see it, the unresolved part (besides cleaning up the Python 2 things) is which Python 3 is minimal for 8.0 and what is the update policy.

2021-06-14 19:46 UTC, veroandreo commented
> > ...I don't like my hot fix...
> 
> My quick guess is that just removing all `HTMLParseError` code is the right solution.
> 
> > I'm closing this PR and we'll revisit this issue later when we go fully Python 3.
> 
> Anytime is fine I think. The master branch is Python 3. The Python 2 compatibility things were not removed, but it is not meant to work with Python 2 and it likely won't. As I see it, the unresolved part (besides cleaning up the Python 2 things) is which Python 3 is minimal for 8.0 and what is the update policy.

Please, have a look/comment here: https://trac.osgeo.org/grass/wiki/RFC/8_LanguageStandardsSupportPython