wxGUI: new design for GNotebooks
OSGeo/grass pull request #1801
Opened 2021-08-17 10:29 UTC by lindakladivova

This PR creates a new design without using an old green color for GNotebooks.
It involves GNotebooks for lmgr, nviz, vnet and dmgr (all notebooks which use globalvar.FNPageColor variable).
I think it is a good idea to have the look of all these notebooks uniform.

Multi-Window GUI lmgr notebook before:
![normalmulti](https://user-images.githubusercontent.com/49241681/129676879-39202dbb-474d-4254-9720-05cfc1489997.PNG)

Now I suggest to change a color to grey:
![multi-180](https://user-images.githubusercontent.com/49241681/129679019-e930bef7-8797-4773-8ade-450fa6f878e3.PNG)

It looks nice for the Single-Window GUI:
![180](https://user-images.githubusercontent.com/49241681/129679082-578a9e43-a213-497b-9cc6-92d3701dd37c.PNG)

The default look for Multi-Window (without any color set) looks as follows:
![bez%barvy_multilayout](https://user-images.githubusercontent.com/49241681/129678996-787b60e4-0ad4-45a4-9079-5c2bcdf2a20c.PNG)
Here, tabs seem to be a bit "swallowed" by the background. 

Similarly the default look for Single-Window:
![withoutcolor](https://user-images.githubusercontent.com/49241681/129679044-21834639-4c5c-4a3d-90da-0bdb5ecf62b9.PNG)

However, we might think about other options.

2021-08-17 11:59 UTC, veroandreo commented
I like the suggestion, the default not so much though. How does it look if the user chooses a dark theme system-wide?

2021-08-17 16:29 UTC, petrasovaa commented
I thought you would also try just regular notebook, so that would be FormNotebook, not GNotebook. The grey looks ok, but I would like to see the dark theme also as Vero suggests.

2021-08-17 17:11 UTC, lindakladivova commented
> 
> 
> I thought you would also try just regular notebook, so that would be FormNotebook, not GNotebook. The grey looks ok, but I would like to see the dark theme also as Vero suggests.

Ok, I will try but I cannot find where or how to set up the dark mode. Can you give me a hint?

2021-08-18 02:33 UTC, petrasovaa commented
> > I thought you would also try just regular notebook, so that would be FormNotebook, not GNotebook. The grey looks ok, but I would like to see the dark theme also as Vero suggests.
> 
> Ok, I will try but I cannot find where or how to set up the dark mode. Can you give me a hint?

Depends on your ubuntu version, I suggest just google it.

2021-08-18 06:59 UTC, lindakladivova commented
> 
> 
> > > I thought you would also try just regular notebook, so that would be FormNotebook, not GNotebook. The grey looks ok, but I would like to see the dark theme also as Vero suggests.
> > 
> > 
> > Ok, I will try but I cannot find where or how to set up the dark mode. Can you give me a hint?
> 
> Depends on your ubuntu version, I suggest just google it.

Great, I thought that it is something related directly to GRASS.
I think it looks good but probably a bigger problem is for MapDisplay AuiNotebook tabs... they really do not look good in the dark mode. What do you think?
![darkmode180](https://user-images.githubusercontent.com/49241681/129852463-e8006790-e7cc-4bc6-a9b0-68d0888e0c8d.PNG)
![darkmode](https://user-images.githubusercontent.com/49241681/129852480-b084a022-f28b-4a03-9900-eb1115995736.PNG)

2021-08-18 11:43 UTC, veroandreo commented
Indeed, map display tabs in the single window output don't look any good in the dark mode. Is is possible to use plain colors instead of the gradient?

2021-08-18 17:56 UTC, petrasovaa commented
> Indeed, map display tabs in the single window output don't look any good in the dark mode. Is is possible to use plain colors instead of the gradient?

Not so easy, it's not easily customizable, one way would be to derive our own AuiTabArt class, that's for later.

2021-08-19 02:40 UTC, petrasovaa commented
> I thought you would also try just regular notebook, so that would be FormNotebook, not GNotebook.

I realized the wx.Notebook doesn't have the right click menu functionality (currently used for renaming). So we would have to deal with that somehow, not sure how, so we might need to stick with FlatNotebook.

2021-08-28 10:19 UTC, lindakladivova commented
Well. I have tried to use the bare style settings without color settings and it looks quite nice for Light mode, but not much for the Dark mode. :-(
Not sure how to go on with the dark mode... I have tried to use System settings, but I would need to use black text color for both cases - dark mode as well as light mode... but the dark one uses white instead of black.

Screenshots:
![pr1801](https://user-images.githubusercontent.com/49241681/131214575-86def754-4f97-46fd-82c3-6fb2095d8ab2.PNG)
![pr1801b](https://user-images.githubusercontent.com/49241681/131214578-3e2d9cee-fac4-4596-bc47-342c63388c87.PNG)

Furthermore, I have noticed there are two interesting options - FNB_HIDE_ON_SINGLE_TAB and FNB_NAV_BUTTONS_WHEN_NEEDED. The first one hides the notebook if there is only one tab, the second one hides the navigation arrows when all tabs fit the space. @petrasovaa  , any suggestions?

2021-08-28 10:25 UTC, lindakladivova commented
I would add, that I personally think that in general tabs and background without gradient look much better so the way we go is likely right.. but for the dark mode it is problematic,

2021-08-29 03:03 UTC, petrasovaa approved these changes
I like it and I also like the option to hide the tab. One display covers majority of cases anyway. I tested that same option for the aui notebook in single window and it looked a little weird so am not sure there.

2021-08-29 09:59 UTC, lindakladivova commented
I removed fancy style for all GNotebooks and set it to normal. There are some screenshots:

**3D View tab:**
![3dview](https://user-images.githubusercontent.com/49241681/131245757-4a0310e3-3257-47cc-8adc-a869464d817c.PNG)
![3dtabdark](https://user-images.githubusercontent.com/49241681/131245765-7d758a94-6867-4e71-a810-2a8dcc2047e0.PNG)

**Web services:**
![webservice2](https://user-images.githubusercontent.com/49241681/131245968-32d06057-85e0-4ce0-ae0d-2ae470f3e7a1.PNG)
![web_service_dark](https://user-images.githubusercontent.com/49241681/131245785-681e1085-caaa-45a8-b8e0-519d5ec3738b.PNG)

**Modeler:**
![modeler](https://user-images.githubusercontent.com/49241681/131245798-207384b8-1792-40a4-aae0-c75ee79e5ec4.PNG)

**Attribute manager:**
Figure 1:
![attribute_manager](https://user-images.githubusercontent.com/49241681/131245806-5e080746-d925-44a4-9de9-2ece7f37bb07.PNG)
Figure 2:
![webservice2](https://user-images.githubusercontent.com/49241681/131246379-974df0a8-fd31-4dca-a871-eea92e648d35.PNG)

Everything looks the same basically - no fancy stuff, no gradients.

However, I am sure about _psmap/frame.py_, _nviz/tools.py_ and sqlNtb in _dbmg/base.py_ - here we have the base **FlatNotebooks**.
You can e.g. notice that the upper notebook in Attribute manager in Figure 1 has a different layout than in Figure 2 where I have set the same settings as for **GNotebooks**. 

Maybe, we could change these three FlatNotebooks to the GNotebooks. What do you think @petrasovaa ?

2021-08-30 03:31 UTC, petrasovaa requested changes
I agree with the changes, and yes, making the FlatNotebooks into GNotebook would make sense.

2021-08-30 03:31 UTC, petrasovaa commented on gui/wxpython/gui_core/forms.py
> +        elif style == 2:  # normal style
Could you completely remove this style? It doesn't make sense to leave it there, it's very similar to the simple top style.

2021-09-02 17:37 UTC, lindakladivova commented
@petrasovaa, I have a problem with the dbmgr InsertNBPage call. It throws this error when clicking on Attribute manager:

Traceback (most recent call last):
  File "/home/linwe/grass/dist.x86_64-pc-linux-
gnu/gui/wxpython/lmgr/frame.py", line 1649, in
OnShowAttributeTable

selection=selection,
  File "/home/linwe/grass/dist.x86_64-pc-linux-
gnu/gui/wxpython/dbmgr/manager.py", line 129, in __init__

self.CreateDbMgrPage(parent=self, pageName="browse")
  File "/home/linwe/grass/dist.x86_64-pc-linux-
gnu/gui/wxpython/dbmgr/base.py", line 831, in
CreateDbMgrPage

parent=parent, parentDbMgrBase=self, onlyLayer=onlyLayer
  File "/home/linwe/grass/dist.x86_64-pc-linux-
gnu/gui/wxpython/dbmgr/base.py", line 1112, in __init__

self.AddLayer(layer)
  File "/home/linwe/grass/dist.x86_64-pc-linux-
gnu/gui/wxpython/dbmgr/base.py", line 1177, in AddLayer

% (layer, label,
self.dbMgrData["mapDBInfo"].layers[layer]["table"]),
  File "/home/linwe/grass/dist.x86_64-pc-linux-
gnu/gui/wxpython/gui_core/widgets.py", line 311, in
InsertNBPage

self.controller.InsertPage(**kwargs)
  File "/home/linwe/grass/dist.x86_64-pc-linux-
gnu/gui/wxpython/gui_core/widgets.py", line 278, in
InsertPage

self.classObject.InsertPage(self.widget, **kwargs)
  File "/usr/lib/python3/dist-
packages/wx/lib/agw/flatnotebook.py", line 4318, in
InsertPage

self.AddPage(page, text, select, imageId)
TypeError
:
AddPage() takes 1 positional argument but 5 were given

I have looked at https://github.com/wxWidgets/Phoenix/blob/master/wx/lib/agw/flatnotebook.py on row 4318, where I obviously need to pass 5 parameters to AddPage method. I have also looked into lmgr/frame.py where this InsertNBPage method is also used. It seems to me, that I call it the same as in lmgr. I am probably missing something but not able to figure out what.

As for psmap and nviz, no special methods from GNotebook class are called. I tested them and it works well.

2021-09-06 03:10 UTC, petrasovaa commented on gui/wxpython/core/settings.py
>              _("List left"),
I wanted to remove the Fancy green, not Basic left, what is supposed to be Normal style?

2021-09-06 03:11 UTC, petrasovaa commented on gui/wxpython/gui_core/forms.py
> -            self.notebook.Bind(wx.EVT_NOTEBOOK_PAGE_CHANGED, self.OnPageChange)
keep this

2021-09-06 03:11 UTC, petrasovaa commented on gui/wxpython/gui_core/forms.py
>              )
remove this

2021-09-06 03:13 UTC, petrasovaa commented on gui/wxpython/gui_core/widgets.py
>      Problems with hidden tabs and does not respect system colors (native look).
Hmm, uses system colours and does not respect system colors at the same time?

2021-09-06 03:16 UTC, petrasovaa commented
> @petrasovaa, I have a problem with the dbmgr InsertNBPage call. It throws this error when clicking on Attribute manager:
> I have looked at https://github.com/wxWidgets/Phoenix/blob/master/wx/lib/agw/flatnotebook.py on row 4318, where I obviously need to pass 5 parameters to AddPage method. I have also looked into lmgr/frame.py where this InsertNBPage method is also used. It seems to me, that I call it the same as in lmgr. But probably missing something and not able to figure it out.

That was little tricky, we were missing *args, since they don't use keyword, but positional arguments in the notebook AddPage call. Please test, I tested it just briefly...

2021-09-06 18:38 UTC, lindakladivova commented
> 
> 
> > @petrasovaa, I have a problem with the dbmgr InsertNBPage call. It throws this error when clicking on Attribute manager:
> > I have looked at https://github.com/wxWidgets/Phoenix/blob/master/wx/lib/agw/flatnotebook.py on row 4318, where I obviously need to pass 5 parameters to AddPage method. I have also looked into lmgr/frame.py where this InsertNBPage method is also used. It seems to me, that I call it the same as in lmgr. But probably missing something and not able to figure it out.
> 
> That was little tricky, we were missing *args, since they don't use keyword, but positional arguments in the notebook AddPage call. Please test, I tested it just briefly...

Great, I will know for the next time when I encounter this. :-) I tested it and it works fine. I think it is ready for merge.

2021-10-05 14:41 UTC, petrasovaa approved these changes

2021-10-05 14:42 UTC, merged