display/d.mon: fix get list of running monitors
OSGeo/grass pull request #1902
Opened 2021-09-29 10:45 UTC by tmszi

**Describe the bug**
List of running monitors from `d.mon -l` is incorrect.

**To Reproduce**
Steps to reproduce the behavior:

1. Launch GRASS GIS `grass80 --text`
2. Start cairo monitor `d.mon start=cairo output=/tmp/map.png`
3. Start another wx0 monitor `d.mon start=wx0`
4. Get list of running monitors `d.mon -l`

```
GRASS nc_spm_08_grass7/landsat:~ > d.mon -l
List of running monitors:
wx0
me/tomas/GIS_ERROR_LOG
```

`me/tomas/GIS_ERROR_LOG` monitor name is incorrect.

**Expected behavior**
Get correct list of running monitors.

```
GRASS nc_spm_08_grass7/landsat:~ > d.mon -l
List of running monitors:
wx0
cairo
```

**Additional context**
Problematic is code line where directory pointer is closed, before access to the array of directories pointers.

Close directory pointer:
https://github.com/OSGeo/grass/blob/38c084ad0b45bc2a46e333eaf4ec5ecabde5d315/display/d.mon/list.c#L65-L69

Access to the array of directories pointers:
https://github.com/OSGeo/grass/blob/38c084ad0b45bc2a46e333eaf4ec5ecabde5d315/display/d.mon/list.c#L86-L87

2021-10-02 16:13 UTC, HuidaeCho commented
interesting.. I cannot reproduce this issue, but I can kind of see a potential issue with just storing pointers. I would `G_store()` `dp->d_name` instead of opening a directory from one function and closing it in another. Please see my comments.

2021-10-02 16:29 UTC, HuidaeCho commented
For our records, `man 3 readdir` says:

> The data returned by readdir() may be overwritten by  subsequent  calls to readdir() for the same directory stream.

and

> On  success,  readdir() returns a pointer to a dirent structure.  (This structure may be statically allocated; do not attempt to free(3) it.)

I think it makes sense to `G_store()` `dp->d_name` because it may be overwritten depending on the implementation.

2021-10-02 16:32 UTC, HuidaeCho requested changes
Please revert all the changes and do `(*list)[*n] = G_store(dp->d_name);`

2021-10-02 16:44 UTC, tmszi commented
> Please revert all the changes and do `(*list)[*n] = G_store(dp->d_name);`

Yes, you're right. I've already fixed it. Thanks.

2021-10-02 16:59 UTC, HuidaeCho approved these changes

2021-10-03 02:25 UTC, merged

2021-10-03 07:55 UTC, nilason commented
@tmszi Please remove the `backport_needed` label after backporting a PR.

2021-10-03 08:34 UTC, tmszi commented
> @tmszi Please remove the `backport_needed` label after backporting a PR.

Ok.