grass.script.array: remove deprecated read function
OSGeo/grass pull request #1926
Opened 2021-10-05 13:38 UTC by petrasovaa

Fixes #925. Changes done in addons in https://github.com/OSGeo/grass-addons/pull/622

2021-12-07 21:17 UTC, wenzeslaus requested changes

2021-12-07 21:17 UTC, wenzeslaus commented on python/grass/temporal/space_time_datasets.py
> +            garray.array3d(self.get_map_id())
`a = ` is missing, but it might be better to just do direct return here anyway. Same for 667 and in RasterDataset on 240 and 242.

2021-12-07 22:03 UTC, wenzeslaus approved these changes

2021-12-08 17:51 UTC, merged

2021-12-08 19:11 UTC, neteler commented
@petrasovaa shall this be backported to 8.0.0?

2021-12-08 20:38 UTC, petrasovaa commented
> @petrasovaa shall this be backported to 8.0.0?

Already done!