wxGUI/main_window: fix close map notebook page
OSGeo/grass pull request #2072
Opened 2022-01-07 07:50 UTC by tmszi

**Describe the bug**
Closing the map notebook page ends with an error message.

**To Reproduce**
Steps to reproduce the behavior:

1. Launch wxGUI with single window mode
2. Try close map notebook page
4. See error

```
Traceback (most recent call last):
  File "/home/tomas/.local/lib/python3.9/site-
packages/wx/core.py", line 3285, in <lambda>

lambda event: event.callable(*event.args, **event.kw) )
  File "/home/tomas/.local/lib/python3.9/site-
packages/wx/lib/agw/aui/auibook.py", line 3685, in
DeletePage

wnd.Destroy()
wx._core
.
wxAssertionError
:
C++ assertion "GetEventHandler() == this" failed at
/tmp/pip-req-build-
oxkmg2wi/ext/wxWidgets/src/common/wincmn.cpp(477) in
~wxWindowBase(): any pushed event handlers must have been
removed
```
**Expected behavior**
Closing the map notebook page should work without an error message. 

**System description:**
- GRASS GIS version main git branch

**Additional context**
Only in single window mode.

2022-01-07 19:04 UTC, petrasovaa commented
There is also #1789.

2022-01-07 20:02 UTC, lindakladivova requested changes
I tried to directly push changes into the your PR @tmszi  but it did not work, so I am putting it here. You can test it, when you switch map notebook tabs and then close the given map notebook tab it should close the right display tab - for me it works good.

I would place pgnum_dict (cause map display index can be different from display tab index):
 
main_window/frame.py:  
```
def CanCloseDisplay(askIfSaveWorkspace):
  """Callback to check if user wants to close display.
  Map Display index can be different from index in Display tab."""
  pgnum_dict = {}
  pgnum_dict["display"] = self.notebookLayers.GetPageIndex(page)
  pgnum_dict["mapnotebook"] = self.mapnotebook.GetPageIndex(mapdisplay)
  name = self.notebookLayers.GetPageText(pgnum_dict["display"])
  caption = _("Close Map Display {}").format(name)
  if not askIfSaveWorkspace or (
      askIfSaveWorkspace and self.workspace_manager.CanClosePage(caption)
  ):
      return pgnum_dict
  return None

def _closePageNoEvent(self, pgnum_dict):
    """Close page and destroy map display without
    generating notebook page closing event"""
    self.notebookLayers.Unbind(FN.EVT_FLATNOTEBOOK_PAGE_CLOSING)
    self.notebookLayers.DeletePage(pgnum_dict["display"])
    self.notebookLayers.Bind(FN.EVT_FLATNOTEBOOK_PAGE_CLOSING, self.OnCBPageClosing)
    self.mapnotebook.DeletePage(pgnum_dict["mapnotebook"])
```
mapdisp/frame.py:       
```
def OnCloseWindow(self, event, askIfSaveWorkspace=True):
  """Window closed.
  Also close associated layer tree page
  """
  Debug.msg(2, "MapPanel.OnCloseWindow()")
  if self.canCloseDisplayCallback:
      pgnum_dict = self.canCloseDisplayCallback(askIfSaveWorkspace=askIfSaveWorkspace)
      if pgnum_dict["display"] is not None:
          self.CleanUp()
            if pgnum_dict["display"] > -1:
                self.closingDisplay.emit(pgnum_dict=pgnum_dict)
                # Destroy is called when notebook page is deleted
    else:
        self.CleanUp()
        self.Destroy()
```

2022-01-07 20:13 UTC, lindakladivova commented
> There is also #1789.

That's the first thing. The second one is the switching of map notebook pages. I've shared my code repairing it. Btw @tmszi you've rescued me :-) because I got pretty lost in  #1789. It is indeed unnecessarily complicated.

2022-01-07 20:16 UTC, lindakladivova commented
I have tested the Close current mapdisplay and Close all mapdisplays from Settings and it works also good after above-shared changes. @tmszi please could you also update a list of shorcuts so that the map notebook page can be also closed by CTRL+W shortcut?

2022-01-07 21:24 UTC, tmszi commented
> I tried to directly push my changes into your PR @tmszi but it did not work, so I am putting it here. You can test it, when you switch map notebook tabs and then close the given map notebook tab it should close the right display tab - for me it works good.

All right, I've applied and tested your changes, and it's working as expected :-).

> I would place pgnum_dict (cause map display index can be different from display tab index).

Yes, you're right.

2022-01-07 21:27 UTC, tmszi commented
> > There is also #1789.
> 
> That's the first thing. The second one is the switching of map notebook pages. I've shared my code repairing it. Btw @tmszi you've rescued me :-) because I got pretty lost in #1789. It is indeed unnecessarily complicated.

You are welcome, so together we simplified the code :-).

2022-01-07 21:45 UTC, tmszi commented
> I have tested the Close current mapdisplay and Close all mapdisplays from Settings and it works also good after above-shared changes. @tmszi please could you also update a list of shorcuts so that the map notebook page can be also closed by CTRL+W shortcut?

The keyboard shortcut Ctrl+W (close map notebook page) works for me without any changes.

2022-01-08 07:49 UTC, lindakladivova commented
I just realize that I have used outdated terminology, still living in the time when the Layers tab was called Display, even though it was my own idea to rename the Display back to Layers :-) Please @tmszi could you just replace "Display" with "Layers"? Sorry for the confusion. :-)

2022-01-08 08:05 UTC, lindakladivova commented
> There is also #1789.

It is one thing and the second one is the problem when you switch map notebook tabs.
But @tmszi you rescue me :-) because I got a bit lost in PR #1789. It is unnecessarily complicated.

I tried to incorporate some changes that repair closing when someone switch map notebook pages. Feel free to comment. I think that the whole concept of closing events is a bit strange (we talked about it with @petrasovaa a longer time ago but actually I am not sure what was the result?).

> > I have tested the Close current mapdisplay and Close all mapdisplays from Settings and it works also good after above-shared changes. @tmszi please could you also update a list of shorcuts so that the map notebook page can be also closed by CTRL+W shortcut?
> 
> The keyboard shortcut Ctrl+W (close map notebook page) works for me without any changes.

Right, I have tested all functionalities - normal closing, closing from settings, and CTRL+W shortcut and all works for me as expected :-)

2022-01-08 08:07 UTC, lindakladivova requested changes
I just realize that I have used outdated terminology, still living in the time when the Layers tab was called Display, even though it was my own idea to rename the Display back to Layers :-) Please @tmszi could you just replace "Display" with "Layers"? Sorry for the confusion. :-)

2022-01-08 08:50 UTC, tmszi commented
This commit https://github.com/OSGeo/grass/pull/2072/commits/ce0586d14c04a7f81a70c9935ac24650bb1c9aa8 solve bug with closing map display notebook layers tree page in multi window mode.

2022-01-08 08:56 UTC, tmszi commented
> I just realize that I have used outdated terminology, still living in the time when the Layers tab was called Display, even though it was my own idea to rename the Display back to Layers :-) Please @tmszi could you just replace "Display" with "Layers"? Sorry for the confusion. :-)

Yes I could. Do you mean the name of the map display page (e.g. Map Display 1 -> Map Layers 1)?

2022-01-08 11:28 UTC, lindakladivova commented
> > I just realize that I have used outdated terminology, still living in the time when the Layers tab was called Display, even though it was my own idea to rename the Display back to Layers :-) Please @tmszi could you just replace "Display" with "Layers"? Sorry for the confusion. :-)
> 
> Yes I could. Do you mean name of layers notebook page and name of the map display notebook page (e.g. Map Display 1 -> Map Layers 1)?
> 
> Default:
> 
> ![wxgui_map_display_page](https://user-images.githubusercontent.com/50632337/148639702-8d77aca3-f4ce-47b0-b7d4-6decb3144e51.png)
> 
> Expected:
> 
> ![wxgui_map_display_page_exp](https://user-images.githubusercontent.com/50632337/148640636-9923c79c-a6d1-4a18-815c-e5dc20fb8c00.png)

No, no, sorry, I did not express well, I meant just to have the terminology correct according to https://github.com/OSGeo/grass/pull/1927. So, in the code to change the Display tab name to Layers tab name, e.g. pgnum_dict["layers"]. But it is a detail, if you prefer to let it as it is e.g. pgnum_dict["display"], it is okay. :-)

2022-01-08 11:33 UTC, lindakladivova commented
> > > I just realize that I have used outdated terminology, still living in the time when the Layers tab was called Display, even though it was my own idea to rename the Display back to Layers :-) Please @tmszi could you just replace "Display" with "Layers"? Sorry for the confusion. :-)
> > 
> > 
> > Yes I could. Do you mean name of layers notebook page and name of the map display notebook page (e.g. Map Display 1 -> Map Layers 1)?
> > Default:
> > ![wxgui_map_display_page](https://user-images.githubusercontent.com/50632337/148639702-8d77aca3-f4ce-47b0-b7d4-6decb3144e51.png)
> > Expected:
> > ![wxgui_map_display_page_exp](https://user-images.githubusercontent.com/50632337/148640636-9923c79c-a6d1-4a18-815c-e5dc20fb8c00.png)
> 
> No, no, sorry, I did not express well, I meant just to have the terminology correct according to #1927. So, in the code to change the Display tab name to Layers tab name, e.g. pgnum_dict["layers"]. But it is a detail, if you prefer to let it as it is e.g. pgnum_dict["display"], it is okay. :-)

I have looked that you put a good explanation of the dictionary into the docs, so you can let it as it is probably. :-)

2022-01-08 12:58 UTC, tmszi commented
> No, no, sorry, I did not express well, I meant just to have the terminology correct according to #1927. So, in the code to change the Display tab name to Layers tab name, e.g. pgnum_dict["layers"]. But it is a detail, if you prefer to let it as it is e.g. pgnum_dict["display"], it is okay. :-)

Yes, you're right. I changed the display dictionary key name to layers in this commit https://github.com/OSGeo/grass/pull/2072/commits/fee16afec4d30086940715f2a45428546060cdc3.

2022-01-08 13:13 UTC, lindakladivova approved these changes

2022-01-09 05:16 UTC, merged