CI: Ignore in GHA CI yml files HTML, Markdown, or Text changes
OSGeo/grass pull request #2176
Opened 2022-02-06 17:31 UTC by neteler

Do not run CI runners on PR when only HTML, Markdown, or txt is changed (inspired by #1778).

Closes #2175 (replacement)

Fixes issue #2174

2022-02-06 19:50 UTC, neteler commented
For some reason the `flake8` and `gnu99` pipelines are not triggered...

2022-02-12 15:30 UTC, neteler commented
@wenzeslaus is there a way to trigger the CI? I'd like to merge this PR but that's blocked...

2022-02-12 20:54 UTC, wenzeslaus commented
The tests never executed. Similar situation is in #2170. Both change workflows, but otherwise unrelated, so perhaps there was or is an issue with GitHub Actions. What seemed to help in #2170 at one point was to make additional commits to the branch. You can also rebase or merge main to add a real commit without making real changes.

2022-02-12 21:18 UTC, wenzeslaus requested changes
What is the reasoning for ignores in each of these workflows? For example, compilation was many times broken in the past due to bad HTML. Additionally, some checks may check some of these file types in the future; thinking Super-Linter and Markdown here.

I don't know if a required check is ignored, whether a PR merge is allowed or impossible?

The syntax is wrong (which might be part of the reason the workflows don't show up at all). It is not valid YAML (try e.g., http://www.yamllint.com/ which gives: _mapping values are not allowed in this context_). `paths-ignore` is part of a mapping (dictionary), but there is no mapping here, only a list of strings.

[GitHub documentation](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#example-excluding-paths) has the following example which suggests that you need to switch the whole content of `on` into a mapping:

```yaml
on:
  push:
    paths-ignore:
      - 'docs/**'
```

WordPress has a good example of a workflow in their [trac](https://core.trac.wordpress.org/browser/trunk/.github/workflows/coding-standards.yml).

2022-02-13 20:13 UTC, neteler commented
Thanks for your explanations.
However, as being not experiences enough with the workflow code I'll drop this PR (I was just annoyed to wait several hours for being able to merge a small update in `doc/howto_release.md`).

2022-02-13 20:13 UTC, closed without merging

2022-02-15 19:26 UTC, wenzeslaus commented
To address your issue, I changed the settings to not require status checks, but only require pull requires for the main branch. This was not possible in GitHub in the past.

Now you don't have to wait for any checks to run because no checks are required. The idea is, of course, that you wait for the relevant checks.

Previously, with Flake8 and one GCC checks required, we ensured that the code at least compiles and it is a valid Python. Black or other checks would practically finish in the meantime too raising red flags if needed. Now you have the responsibility to determine what is needed.

Generally, PRs feature asynchronous workflows, so the expectation is that the code will sit in the PR for some time.

2022-02-15 20:49 UTC, neteler commented
Thanks, @wenzeslaus - so: "handle with care!".