g.extension: better handle request exceptions for l flag
OSGeo/grass pull request #2203
Opened 2022-02-13 09:11 UTC by tmszi

**Describe the bug**
When you disable internet connection and try download list of available addons via `g.extension -l` module, g.extension will try download module.xml file for GRASS GIS 7.8 version (see URL address in error message), due wrong handled request exception on line 254, before try to dowlnoad this file.

https://github.com/OSGeo/grass/blob/f720e3eba5d1462ad0b37f2b020c15f05870b05d/scripts/g.extension/g.extension.py#L247-L256

**To Reproduce**
Steps to reproduce the behavior:

1. Disable your internet connection
2. Launch `g.extension -l`
4. See error (request exception is handed correctly here, but URL address is incorrect due another request exception before this (line 254) is wrong handled.

```
GRASS nc_basic_spm_grass7/PERMANENT:~ > g.extension -l
List of available extensions (modules):
ERROR: Download file from
       <https://grass.osgeo.org/addons/grass7/modules.xml> failed. Check
       your internet connection.
```

https://grass.osgeo.org/addons/grass7/modules.xml -> **grass7**

**Expected behavior**
Correctly handled exception if internet connection is not available inside [get_version_branch()](https://github.com/OSGeo/grass/blob/f720e3eba5d1462ad0b37f2b020c15f05870b05d/scripts/g.extension/g.extension.py#L247-L256) function.

Error message should be:

```
GRASS nc_basic_spm_grass7/PERMANENT:~ > g.extension -l
ERROR: You are not connected to the internet. Check your internet
       connection.
```

**System description:**

- GRASS GIS version: main, realesebranch_7_8, realesebranch_8_0

2022-02-16 20:53 UTC, ninsbl approved these changes
I did not test locally, but it looks good to me.

2022-03-17 03:12 UTC, wenzeslaus requested changes
Given the errors we see elsewhere, I think adding the original error message to the message is needed (`our text: {err}`) to provide as much details as possible (or to not assume too much when we don't know the details).

2022-03-17 03:12 UTC, wenzeslaus commented on scripts/g.extension/g.extension.py
>      except URLError:
`as error` needed and then use it later.

2022-03-17 03:12 UTC, wenzeslaus commented on scripts/g.extension/g.extension.py
>      except URLError:
`as error` needed and then use it later.

2022-03-17 03:12 UTC, wenzeslaus commented on scripts/g.extension/g.extension.py
> +                    "{base_message}, {err}. ".format(
Why comma here? Probably, neither `,` nor `.` are needed here. It should be `"{base_message}: {err}"`.

2022-03-17 03:12 UTC, wenzeslaus commented on scripts/g.extension/g.extension.py
> +                " internet connection."
`your "` and `" internet"`: only one space is needed.

2022-03-17 03:12 UTC, wenzeslaus commented on scripts/g.extension/g.extension.py
> +    base_message = "Download file from <{url}> failed".format(url=url)
Needs to be translatable too if you want that to be translatable (I assume yes).

2023-02-18 10:25 UTC, neteler commented
@tmszi Would you mind to address the comments? Most look like easy to fix.

2023-05-12 22:12 UTC, wenzeslaus commented
Current error message for g.extesnion is:

```
$ grass --tmp-location XY --exec g.extension -l
ERROR: Failed to get branch from the Git repository
       <https://github.com/OSGeo/grass-addons/>.
       fatal: unable to access 'https://github.com/OSGeo/grass-addons/':
       Could not resolve host: github.com
```

This does not include "You are not connected to the internet. Check your internet connection." like the suggested message. However, the handling is done in a different way which is what this PR was mostly doing.

The code on main changed completely and the review comments here don't make any sense anymore. I suggest closing this PR.

2023-05-17 14:20 UTC, wenzeslaus commented
As I mentioned in my previous comment, this is resolved by other code changes.

Follow with some separate message cosmetics PR if needed.

2023-05-17 14:20 UTC, closed without merging