Use SRID for PJ object creation when possible
OSGeo/grass pull request #2394
Opened 2022-05-23 06:32 UTC by HuidaeCho

This PR tries to address #2257 by using SRID, not GRASS key-value pairs, for creating an PJ object. Here is [a related Q&A](https://geopandas.org/en/stable/docs/user_guide/projections.html#i-get-a-bound-crs).

2022-05-27 16:46 UTC, metzm requested changes
The idea is correct, but this PR does not fix cases where no SRID is available and a bound CRS is provided. Should be easy to add.

2022-05-27 16:46 UTC, metzm commented on lib/proj/get_proj.c
> +        (!info->srid && !(pj = proj_create_argv(pjc, nopt, opt_in)))) {
I recommend to first create a PJ object and then recycle the code at https://github.com/OSGeo/grass/blob/main/lib/proj/do_proj.c#L332 to check if it is a `PJ_TYPE_BOUND_CRS`, in which case the source crs should be retrieved.

Applies not only to `pj_get_kv()`, but also to  `pj_get_string()`

2022-05-30 18:16 UTC, HuidaeCho commented
@metzm Do we ever hit this PROJ error when `pj` is already not `NULL`?
https://github.com/OSGeo/grass/blob/830f31d215038c1a67112aa350619f652e04e70b/lib/proj/get_proj.c#L275-L278

2022-06-01 04:07 UTC, HuidaeCho commented
> @metzm Do we ever hit this PROJ error when `pj` is already not `NULL`?
> 
> https://github.com/OSGeo/grass/blob/830f31d215038c1a67112aa350619f652e04e70b/lib/proj/get_proj.c#L275-L278

I think we can remove this check.

https://proj.org/development/reference/functions.html#c.proj_create_argv

> If creation of the transformation object fails, the function returns 0 and the PROJ error number is updated.

2022-07-01 16:47 UTC, metzm commented
Apparently `proj_errno(pj)` can still return an error code, if `pj` is not NULL. At least this is used in various places in PROJ itself.

2022-07-01 16:48 UTC, metzm approved these changes
Thanks for the fix! This will not be the only one regarding the evolving PROJ lib I guess...

2023-01-10 19:45 UTC, merged