init: Fix sudo message on Ubuntu
OSGeo/grass pull request #2532
Opened 2022-08-20 18:05 UTC by susi

Fixes #753 by creating `<mapset>/.sudo_as_admin_successful` when `$HOME/.sudo_as_admin_successful` exists

2022-08-28 09:10 UTC, wenzeslaus requested changes
Can you please add a comment to the code explaining what it is about, so that one does not have to go all the way to the GitHub issue to see reasoning for this?

Advantages of new file versus copying the file is not clear to me. Either one works at this point I guess.

The Black reformat is unfortunate, but given your plans to restructure grass.py, I think it is fine to leave it here although it unrelated.

2022-08-28 13:05 UTC, susi commented
Added a massive explanation :stuck_out_tongue:

2022-08-28 14:49 UTC, wenzeslaus commented on lib/init/grass.py
> +        # Ubuntu sudo creates a file .sudo_as_admin_successful and cbash checks
cbash, typo or a thing?

2022-08-28 15:20 UTC, susi commented on lib/init/grass.py
> +        # Ubuntu sudo creates a file .sudo_as_admin_successful and cbash checks
It's a typo...

2022-10-07 02:50 UTC, wenzeslaus approved these changes

2022-10-07 03:11 UTC, merged