contributing: Improve where doc is located
OSGeo/grass pull request #2535
Opened 2022-08-24 15:22 UTC by wenzeslaus

* Move C API doc compilation from readme.
* Move compilation intro to the end of contributing file.

2022-08-24 16:20 UTC, veroandreo requested changes
I'll continue after the Ice-breaker.... ehehehe

2022-08-24 16:20 UTC, veroandreo commented on CONTRIBUTING.md
> +Notably, you should not make commits to your main branch,
```suggestion
Notably, you should not make commits to your local main branch,
```

2022-08-24 16:20 UTC, veroandreo commented on CONTRIBUTING.md
> +so the above is than just a simple update (and no actual
```suggestion
so the above is then just a simple update (and no actual
```

2022-08-24 16:20 UTC, veroandreo commented on CONTRIBUTING.md
>  ### Update if you have local branches
```suggestion
### Update if you have local changes
```

2022-08-24 16:20 UTC, veroandreo commented on CONTRIBUTING.md
> +There is a series of automated checks which will run you pull request
```suggestion
There is a series of automated checks which will run on your pull request
```

2022-08-24 16:20 UTC, veroandreo commented on CONTRIBUTING.md
> +after you create that later on. You don't need to run every one of these
```suggestion
after you create one. You don't need to run all these
```

2022-08-24 16:20 UTC, veroandreo commented on CONTRIBUTING.md
> +checks locally and some of these may fail for your code. This is a part of
```suggestion
checks locally and, indeed, some of them may fail for your code. This is a part of
```

2022-08-24 16:20 UTC, veroandreo commented on CONTRIBUTING.md
> +the standard iterative process of interating changes into the main code,
```suggestion
the standard iterative process of integrating changes into the main code,
```

2022-08-26 16:27 UTC, veroandreo reviewed
done :)

2022-08-26 16:27 UTC, veroandreo commented on CONTRIBUTING.md
> +and try again. If you are not sure what to do, let other know in a pull
```suggestion
so if that happens, just see the error messages, go back to your code
and try again. If you are not sure what to do, let others know in a pull
```

2022-08-26 16:27 UTC, veroandreo commented on CONTRIBUTING.md
> +There are some steps you can do locally, to improve your code.
```suggestion
Note that there are some steps you can do locally to improve your code.
```

2022-08-26 16:27 UTC, veroandreo commented on CONTRIBUTING.md
> +you may improve your code.
```suggestion
also run linter tools such as Pylint which will suggest different improvements 
to your code.
```

2022-08-26 16:27 UTC, veroandreo commented on CONTRIBUTING.md
> +for most operating systems in our wiki:
```suggestion
to install dependencies and compile GRASS source code for most operating systems.
Please see our dedicated wiki:
```

2022-08-27 10:01 UTC, veroandreo approved these changes

2022-08-27 18:05 UTC, neteler approved these changes

2022-08-28 11:40 UTC, merged