build_modules_xml.py, grass.py: catch errors
OSGeo/grass pull request #2686
Opened 2022-12-06 10:43 UTC by neteler

This PR is an extract from #348 (extracted and updated with `black`):

- gui/wxpython/tools/build_modules_xml.py edits:
    - https://github.com/OSGeo/grass/pull/348/files#diff-11ca77721b6d009b6537c54be4172efed843021797676258ad1141a6c63e6fd1
- lib/init/grass.py edit:
   - https://github.com/OSGeo/grass/pull/348/files#diff-647be4ef599868c33f2f69f0d899f79f0aee8d75d1db74f523268c1ac94cddf7

Not sure if we want these changes but just to avoid to see them lost when closing #348 in favour of #2684.

2022-12-23 15:49 UTC, wenzeslaus requested changes
Generally, this looks good.

I'm not sure about managing these small changes smartly for the release notes. It does not fit into these categories:

https://github.com/OSGeo/grass/blob/main/utils/release.yml

2022-12-23 15:49 UTC, wenzeslaus commented on lib/init/grass.py
> +    if not LD_LIBRARY_PATH_VAR == "":
Simpler:

```suggestion
    if LD_LIBRARY_PATH_VAR:
```

2023-01-12 10:15 UTC, neteler commented
> I'm not sure about managing these small changes smartly for the release notes.

I have changed to use the "startup: ..." keyword.

2023-01-28 10:39 UTC, neteler commented
@wenzeslaus may I merge this PR? Not sure how to properly dismiss the "Changes requested" which I believe have been addressed.

2023-02-13 18:51 UTC, wenzeslaus approved these changes

2023-02-13 19:46 UTC, merged