CI: Switch Travis to Ubuntu 22.04 (jammmy)
OSGeo/grass pull request #3002
Opened 2023-06-04 09:29 UTC by wenzeslaus

Default Python version reported by Travis for 20.04 is 3.7.13. While that's still a supported version for 8.3 release if it would be released now, 2023-06-27 is end of support for 3.7, so it seems safe to not test the main branch with 3.7 at this point.

Ubuntu 22.04 in Travis uses Python 3.10 by default according to the documentation.

2023-11-19 11:11 UTC, landam approved these changes

2023-11-19 11:12 UTC, landam requested changes
Conflicts must be solved.

2023-12-23 15:42 UTC, echoix commented
I verified that the file used that lists the dependencies included the change that was conflicting, it removed python-six and python-six was also removed from that file.

2023-12-23 17:29 UTC, echoix requested changes
I investigated the Travis failure and include a fix, but needs to be committed as I can't add an suggestion on lines not changed in the PR.

2023-12-23 17:29 UTC, echoix commented on .travis/linux.install.sh
I figured out what was the failure. Since in theory, the part of the script that is used in GitHub actions works, it should work here.
I ended up using shellsheck to finally point me to the cause. (They also have a web interface, but it's a linter)
![image](https://github.com/OSGeo/grass/assets/27212526/d84002af-6cec-46ff-b9f9-aa43d4c27592)
More info about the problem can be read here: https://www.shellcheck.net/wiki/SC3001

So, the process substitution doesn't work because of the shebang. Since this script is only used for Travis, the easiest fix to change the shebang won't be an issue.
```diff
-#!/usr/bin/env bash
+#!/usr/bin/env bash
 # Author: Ivan Mincik, ivan.mincik@gmail.com
```

So the file should be:

```shell
#!/usr/bin/env bash
# Author: Ivan Mincik, ivan.mincik@gmail.com

set -e

sudo apt-get update -y
    sudo apt-get install -y wget git gawk findutils
    xargs -a <(awk '! /^ *(#|$)/' ".github/workflows/apt.txt") -r -- \
        sudo apt-get install -y --no-install-recommends --no-install-suggests
```

I can't add an inline suggestion since it is out of the lines changed in this PR.
If we use this fix, we might as well apply it to the three Travis scripts.

The other workaround if plain POSIX sh shell is needed is to use a temporary file, as illustrated in the rule documentation I linked above.

2023-12-27 02:17 UTC, echoix commented
@wenzeslaus I made a PR to your branch with the fixes that I found were needed but couldn't apply a suggestion on the lines. 

https://github.com/wenzeslaus/grass/pull/3

2024-02-08 05:51 UTC, echoix commented
Pinging back, so you could take a look at the PR in your fork targetting this branch, at the time that I made the changes it would have fixed the blockers in the PR and would make it ready to merge.

2024-02-09 02:00 UTC, wenzeslaus commented on .travis/linux.install.sh
Using Bash makes more sense here. We are using it elsewhere and we don't have a reason to stick to sh.

2024-02-09 02:16 UTC, wenzeslaus commented
Thanks @echoix. The Bash helped. If you want to take over here. Feel free to edit the branch directly. In any case, the current state is that it fails with PDAL (I didn't investigate):

```
checking whether to use PDAL... yes
configure: error: *** Unable to locate suitable (>=1.7.1) PDAL library.
```

2024-02-09 04:19 UTC, echoix commented
Can you make sure that the box allow edits by maintainers is checked? I think I tried and it didn't work at the time

2024-02-14 02:30 UTC, echoix submitted a review, later dismissed

2024-02-14 03:25 UTC, wenzeslaus commented
Both are on "Maintainers are allowed to edit this pull request." and "Allow edits and access to secrets by maintainers"

2024-03-11 11:55 UTC, echoix commented
I'm investigating on lost time here and then when I get an idea.

What I realized is that on Github CI, we use pdal 2.3.0 from ubuntu jammy. We never really built with pdal 2.6.2. Are we sure that our conifgure script works with pdal 2.6.3, or anything past 2.3.0? If someone could answer that, it might save me a little investigation instead of trying to get that answer by myself.

2024-03-11 13:20 UTC, neteler commented
I have tried your changes in a `ubuntu:jammy` docker session and all got installed (PDAL 2.3.0).
On my local Fedora box I have PDAL 2.5.6. No experience yet with 2.6.3 but why should it be a problem (now)?

According to https://repology.org/project/pdal/versions a few distros already include  2.6.3 but I didn't try that.

2024-03-11 13:30 UTC, echoix commented
It's (one of) the only place where we are building with ubuntugis unstable. Ubuntugis unstable gives 2.6.3. It had a new build between Thursday and this weekend, since a problem with a plugin package caused QGIS problems. But it shouldn't be that related, it was CMake stuff if I understand correctly.

I don't know the purpose of the Travis builds, so at least keeping it different of the GitHub Actions builds we already is important I think.

2024-03-13 17:53 UTC, wenzeslaus commented
> I don't know the purpose of the Travis builds,

The Travis build was there before GitHub Actions were available. Then there was some time when GHA were broken and Travis provided the only (backup?) CI check (visual and doable as there were no required checks). Now perhaps, the value is in having another CI in place, so if our primary one goes away, we have a backup ready to go. I think I have seen even with Travis, but definitively in other cases that differences in configuration or tooling (and some duplication) make the CI more robust overall (e.g., one run is okay but another fails because of just slightly older dependency).

> so at least keeping it different of the GitHub Actions builds we already is important I think.

That seems to be a valid approach. ...if you think it is not too much trouble for the one or two above values it provides.

2024-03-21 21:32 UTC, echoix commented
Ok, it seems like an incompatibility of some sort with a newer PDAL or with the ubuntugis PPA (that provides a newer PDAL version). Disabling the ubuntugis ppa allows the ./configure call to succeed. It shouldn’t be an issue limited to Travis. It should be possible to reproduce somewhere else.

Our builds not being successful with the Ubuntugis ppa is somewhat problematic in my opinion

2024-03-22 16:47 UTC, neteler commented
> Ok, it seems like an incompatibility of some sort with a newer PDAL or with the ubuntugis PPA (that provides a newer PDAL version).

Is the error anywhere visible?

PDAL 2.7.0 just hit Fedora (https://src.fedoraproject.org/rpms/PDAL/c/3f731663ed3cbd4fbbacf475c1fb9a1bb0492b24?branch=rawhide), apparently without problems.

2024-06-18 19:45 UTC, wenzeslaus reviewed
I can only comment as a co-author, but I approve. I don't know why the functions need to be fixed only now, but I assume we compile without ODBC in GitHub Actions CI.

2024-06-18 19:47 UTC, wenzeslaus commented
@landam Please, check this.

2024-06-19 08:06 UTC, echoix commented
The -Wdeprecated-non-prototype errors are now fixed and clang and gcc pass Travis builds using -Werror. Ready to merge.

Does the title need to change to say some c files were changed?

2024-06-19 09:28 UTC, wenzeslaus reviewed
Approved as much as I can.

2024-06-19 09:29 UTC, echoix approved these changes
Reviewed with Vaclav, as he can't approve a PR opened by himself, I'm setting the approval

2024-06-19 09:30 UTC, merged