wxGUI: Default Single-Window size is too small
OSGeo/grass pull request #3024
Opened 2023-06-05 11:48 UTC by lindakladivova

Fixes https://github.com/OSGeo/grass/issues/3013

2023-06-06 11:50 UTC, pesekon2 commented
Fixes the problem for me. @tmszi does it fix also your `TypeError` from #3013?

2023-06-06 13:19 UTC, lindakladivova commented
> Fixes the problem for me. @tmszi does it fix also your `TypeError` from #3013?

@pesekon2 Most likely, it is not going to help. The MenuItem error has nothing to do with the size of Single Window. I would suggest creating a different PR for it.

2023-06-06 15:53 UTC, petrasovaa commented
Should this go to 8.3 release? It looks like a an important fix. Why is it draft? The TypeError is unrelated.

2023-06-06 19:03 UTC, lindakladivova commented
> Should this go to 8.3 release? It looks like a an important fix. Why is it draft? The TypeError is unrelated.

Yes, it should go to the release 8.3.0, I initially set it up for version 8.3.0.

This is a draft because I would like to test it more (it was very fast written).

2023-06-07 14:11 UTC, landam commented
Single Window should probably start maximized by default. @lindakladivova @petrasovaa Any opinion?

2023-06-07 19:54 UTC, tmszi commented
> Well @landa, it actually is maximized by default but the problem is that we take the parameter defWindowPos (set by globalvar.GM_WINDOW_SIZE variable) from UserSettings if defined (rows 181 - 196). You can go to Settings -> General -> and check Suppress positioning Layer Manager window, close GRASS and start again and it will launch as maximized.

By default without using this PR, single window mode size depend on the DE, respectively the type of window layout (floating, tiled, monocle) and OS wxGTK, wxMSW.

wxMSW (floating windows layout) default single window size and position:

![wxmsw_swm_size_pos_floating](https://github.com/OSGeo/grass/assets/50632337/e2a4ebc0-260b-4ec8-a0f7-b7a29343ffd8)

wxGTK (floating windows layout with dwm window manager) default single window size and position (issue #3013):

![wxgtk_smw_size_pos_dwm_floating](https://github.com/OSGeo/grass/assets/50632337/aed0a71f-f12d-4cc6-bc69-fb6422b8b216)

wxGTK (floating windows layout with Gnome DE) default single window size and position:

![wxgtk_smw_size_pos_gnome_floating](https://github.com/OSGeo/grass/assets/50632337/b8b5fb4c-bd63-4f2a-9fcd-1c3faa157c31)

Important user settings is **Save current window layout as default** which works as expected. You can change position and size of window (single window mode too).

> IMHO This User setting does not make sense for Single-Window, I would suggest removing rows 181 - 196 in frame/main_window.py. @petrasovaa what do you think?

It is not a good idea, if you remove these lines, the wxGUI single window mode will not respect the client area and will be overlapped by the DE panel(s).

2023-06-08 07:08 UTC, pesekon2 commented
> Further, I have one more thing here, I would like to try to suppress the GTK warnings as @vero mentioned... it is also painful but I will at least try it and we will see..

This would be the best thing to happen in GRASS for many years, in my eyes (I have the experience that when the users see those warnings and criticals, they consider GRASS to be broken and stop using it). Have had a discussion about that with @wenzeslaus and he can give a verbose, loquacious monologue on that. But we shouldn't make this issue a discussion forum keep sticking to the topic.

2023-06-08 18:55 UTC, tmszi commented
Seems it is regression between revisions (respectively GRASS GIS versions)

1. Single window mode launch in the full screen mode by default with GRASS GIS version [8.3.0dev](https://grass.osgeo.org/grass83/binary/linux/snapshot/)

wxGTK (floating windows layout with Gnome DE) default single window size and position:

![wxgtk_swm_def_pos_size_floating](https://github.com/OSGeo/grass/assets/50632337/7299ff15-c739-4482-937f-37b81fc4b70a)

```
GRASS world_latlong_wgs84/PERMANENT:~ > g.version -g
version=8.3.0dev
date=2023
revision=567ea066bd
build_date=2023-06-07
```

2. Single window mode doesn't  launch in the full screen mode by default with GRASS GIS version [8.4.0dev](https://grass.osgeo.org/grass84/binary/linux/snapshot/)

wxGTK (floating windows layout with Gnome DE) default single window size and position:

![wxgtk_swm_def_pos_size_floating](https://github.com/OSGeo/grass/assets/50632337/09ef3aaf-f59a-484a-bc79-079ed30dde20)


```
GRASS world_latlong_wgs84/PERMANENT:~ > g.version -g
version=8.4.0dev
date=2023
revision=24fd2a38f4
build_date=2023-06-08
```

2023-06-09 15:12 UTC, lindakladivova commented
> 

@tmszi  I will try to explain how I understand the problem, I might be wrong, please correct me.

The size of wx.Frame is in the constructor given by wx.Display().GetGeometry().GetSize() by default (in my case e.g. (1920, 1080)).

But the problem is that after calling self.Fit(), for some reason, the size of the main window is being changed and this is why I removed all self.Fit() callings. Not sure what happened between 8.3.0dev and 8.4.0dev versions but suddenly self.Fit() did not work.

But! When I tested this Pull request I was quite annoyed by the fact that even after removing the Fit() calling, I cannot reach the maximized extent (1920, 1080). The problem was that I was actually still overwriting the desired extent by the extent I had saved in the UserSettings (rows 181-197).

Maybe I am not right, but I think that using just wx.Display().GetGeometry().GetSize() could be enough for setting the size of the main window. (I went from the fact that also other software I use always starts over the whole screen at the beginning), I think that making Single-Window smaller and saving this into the User Settings does not make much sense...

But we can let it as it is, I have no problem with that. I was just critically thinking about the code and if these 17 rows have some meaning..

2023-06-09 15:19 UTC, lindakladivova commented
> > Further, I have one more thing here, I would like to try to suppress the GTK warnings as @vero mentioned... it is also painful but I will at least try it and we will see..
> 
> This would be the best thing to happen in GRASS for many years, in my eyes (I have the experience that when the users see those warnings and criticals, they consider GRASS to be broken and stop using it). Have had a discussion about that with @wenzeslaus and he can give a verbose, loquacious monologue on that. But we shouldn't make this issue a discussion forum keep sticking to the topic.

I have spent two hours thinking about how to suppress these GTK warnings when launching GRASS and no results. I just succeed in making more of them :)...

2023-06-10 06:17 UTC, wenzeslaus commented
> > > ...I would like to try to suppress the GTK warnings as @vero mentioned... it is also painful but I will at least try it and we will see..
> > 
> > This would be the best thing to happen in GRASS for many years, in my eyes (I have the experience that when the users see those warnings and criticals, they consider GRASS to be broken and stop using it). Have had a discussion about that with @wenzeslaus and he can give a verbose, loquacious monologue on that...
> 
> ...I have spent two hours thinking about how to suppress these GTK warnings when launching GRASS and no results...

#3049 removes the stderr when GUI is started together with GRASS GIS (not for g.gui).

2023-06-10 07:36 UTC, tmszi commented
> > 
> 
> @tmszi I will try to explain how I understand the problem, I might be wrong, please correct me.
> 
> The size of wx.Frame is in the constructor given by wx.Display().GetGeometry().GetSize() by default (in my case e.g. (1920, 1080)).
> 
> But the problem is that after calling self.Fit(), for some reason, the size of the main window is being changed and this is why I removed all self.Fit() callings. Not sure what happened between 8.3.0dev and 8.4.0dev versions but suddenly self.Fit() did not work.
> 
> But! When I tested this Pull request I was quite annoyed by the fact that even after removing the Fit() calling, I could not reach the maximized extent (1920, 1080). The problem was that I was actually still overwriting the desired extent by the extent I had saved in the UserSettings (rows 181-197).
> 
> Maybe I am not right, but I think that using just wx.Display().GetGeometry().GetSize() could be enough for setting the size of the main window. (I went from the fact that also other software I use always starts over the whole screen at the beginning), I think that making Single-Window smaller and saving the adapted extent into the User Settings does not make much sense...
> 
> But we can let it as it is, I have no problem with that. I was just critically thinking about the code and if these 17 rows have some meaning..

@lindakladivova First thanks for your explanation.

I attached my patch which solve two issues:

1. Maximize single window mode by default
2. Respect user custom window position and size (custom win pos and size for single win mode is saved as standalone settings separate from multi win mode settings) changed via wxGUI Preference dialog **Save current window layout as default** checkbox widget

`git am 0001-wxGUI-main_window-maximize-window-by-default.patch`

[0001-wxGUI-main_window-maximize-window-by-default.patch.zip](https://github.com/OSGeo/grass/files/11711847/0001-wxGUI-main_window-maximize-window-by-default.patch.zip)

2023-06-18 10:21 UTC, lindakladivova commented
> > > 
> > 
> > 
> > @tmszi I will try to explain how I understand the problem, I might be wrong, please correct me.
> > The size of wx.Frame is in the constructor given by wx.Display().GetGeometry().GetSize() by default (in my case e.g. (1920, 1080)).
> > But the problem is that after calling self.Fit(), for some reason, the size of the main window is being changed and this is why I removed all self.Fit() callings. Not sure what happened between 8.3.0dev and 8.4.0dev versions but suddenly self.Fit() did not work.
> > But! When I tested this Pull request I was quite annoyed by the fact that even after removing the Fit() calling, I could not reach the maximized extent (1920, 1080). The problem was that I was actually still overwriting the desired extent by the extent I had saved in the UserSettings (rows 181-197).
> > Maybe I am not right, but I think that using just wx.Display().GetGeometry().GetSize() could be enough for setting the size of the main window. (I went from the fact that also other software I use always starts over the whole screen at the beginning), I think that making Single-Window smaller and saving the adapted extent into the User Settings does not make much sense...
> > But we can let it as it is, I have no problem with that. I was just critically thinking about the code and if these 17 rows have some meaning..
> 
> @lindakladivova First thanks for your explanation.
> 
> I attached my patch which solve two issues:
> 
>     1. Maximize single window mode by default
> 
>     2. Respect user custom window position and size (custom win pos and size for single win mode is saved as standalone settings separate from multi win mode settings) changed via wxGUI Preference dialog **Save current window layout as default** checkbox widget
> 
> 
> `git am 0001-wxGUI-main_window-maximize-window-by-default.patch`
> 
> [0001-wxGUI-main_window-maximize-window-by-default.patch.zip](https://github.com/OSGeo/grass/files/11711847/0001-wxGUI-main_window-maximize-window-by-default.patch.zip)

@tmszi  Thanks for sharing it. I think now, it is more clear what is going on. I have used your changes and made little fixes [73fb223](https://github.com/OSGeo/grass/pull/3024/commits/73fb223d05ff5250d2bc29d9eda98bc12fa57180). Please look at them and if alright from your side, we could merge this.

2023-06-18 12:19 UTC, landam commented
I tested PR on Debian testing (Gnome). Before starting GRASS I have deleted wx settings. Single layout started maximized as expected. Can we merge PR and backport to 8.3?

2023-06-18 12:19 UTC, landam approved these changes

2023-06-18 13:51 UTC, pesekon2 commented
Starting the GUI maximized solves the issue for me too.

2023-06-18 13:51 UTC, pesekon2 approved these changes

2023-06-18 13:51 UTC, tmszi commented
Tested on Gentoo with [dwm](https://dwm.suckless.org/) with activated float window mode and wxGUI has been launched maximized by default and custom user settings (win position and size) works as expected too.

2023-06-18 20:42 UTC, petrasovaa requested changes
I tested this with multi-window and currently it ignores the map display size and position, because `IsDocked` is True for mutli-window. This should fix it:

```
--- a/gui/wxpython/gui_core/preferences.py
+++ b/gui/wxpython/gui_core/preferences.py
@@ -1853,7 +1853,9 @@ class PreferencesDialog(PreferencesBaseDialog):
 
                 # window size must be larger than zero, not minimized
                 # do not save dim when mapdisp is docked within single window
-                if not mapdisp.IsDocked() and (size[0] > 0 and size[1] > 0):
+                if (not mapdisp.IsDockable() or not mapdisp.IsDocked()) and (
+                    size[0] > 0 and size[1] > 0
+                ):
                     dim += f",{pos[0]},{pos[1]},{size[0]},{size[1]}"
 
             if single_window:
```

2023-06-20 07:10 UTC, landam commented
I tested multi-window with the patch above applied.

1. started GUI in multi-window layout
2. changed windows position
3. go to preferences, save
4. restart GUI

Windows appeared in original position, new position was ignored.

It seems that there is still an issue.

2023-06-20 07:11 UTC, landam requested changes
multi-window position is ignored

2023-06-20 07:15 UTC, landam commented
I have 

```
      "dim": "26,23,634,622",
```

in settings regardless how I organize windows. It seems to be different issue not related to this PR.

2023-06-20 07:22 UTC, landam commented
Strangely, when I change size of windows it works. But position is always the same:

```
26,23,866,802,26,23,951,762
```

2023-06-20 07:28 UTC, landam commented
`GetPosition()` always returns `(26,23)` in my case (wxpython 4.2.0). But it seems to be not related to this PR.

2023-06-20 07:31 UTC, landam commented on gui/wxpython/gui_core/preferences.py
> +                if not mapdisp.IsDocked() and (size[0] > 0 and size[1] > 0):
```suggestion
                if (not mapdisp.IsDockable() or not mapdisp.IsDocked()) and (
                    size[0] > 0 and size[1] > 0
                ):
                     dim += f",{pos[0]},{pos[1]},{size[0]},{size[1]}"
```

2023-06-20 07:55 UTC, nilason commented on gui/wxpython/main_window/frame.py
> +                self.Maximize(True)
`self.Maximize()`is never reached in a "first run" simulation (with no existing`~/.grass8` dir), placing the window partially under the OS menu on Mac:

<img width="282" alt="Screenshot_default" src="https://github.com/OSGeo/grass/assets/14186207/aa3b857c-3c6e-402d-8df0-67963b39e4dd">


Outdenting the `else: self.Maximize()´ seems to work for me :

```py
        if UserSettings.Get(group="general", key="defWindowPos", subkey="enabled"):
            single_window_dim = {
                "group": "general",
                "key": "defWindowPos",
                "subkey": "dimSingleWindow",
            }
            dim = UserSettings.Get(**single_window_dim)
            default_dim = UserSettings.Get(**single_window_dim, settings_type="default")
            if dim != default_dim:
                try:
                    x, y = map(int, dim.split(",")[0:2])
                    w, h = map(int, dim.split(",")[2:4])
                    client_disp = wx.ClientDisplayRect()
                    if x == 1:
                        # Get client display x offset (OS panel)
                        x = client_disp[0]
                    if y == 1:
                        # Get client display y offset (OS panel)
                        y = client_disp[1]
                    self.SetPosition((x, y))
                    self.SetSize((w, h))
                except Exception:
                    pass
        else:
            self.Maximize(True)
```

2023-06-20 16:58 UTC, lindakladivova commented
> `GetPosition()` always returns `(26,23)` in my case (wxpython 4.2.0). But it seems to be not related to this PR.

Yep, that's unrelated (probably a wxPython 4.2.0 error).

2023-06-20 20:03 UTC, petrasovaa commented
> > `GetPosition()` always returns `(26,23)` in my case (wxpython 4.2.0). But it seems to be not related to this PR.
> 
> Yep, that's unrelated (probably a wxPython 4.2.0 error).

For me the position is saved as expected, I also use wxPython 4.2.0, so I am unsure why it doesn't work.

2023-06-20 20:03 UTC, petrasovaa approved these changes

2023-06-20 20:24 UTC, nilason approved these changes

2023-06-21 08:57 UTC, merged

2023-06-21 09:00 UTC, petrasovaa commented
In the interest of timely release I took liberty to merge and backport to 8_3 branch.