wxGUI/lmgr: fix saving web service layer as raster map
OSGeo/grass pull request #3101
Opened 2023-07-26 18:08 UTC by tmszi

**Describe the bug**
Saving web service layer as raster map fail.

**To Reproduce**
Steps to reproduce the behavior:

1. From the GUI Layers pane toolbar launch Add web service map dialog
2. Hit Add default button
3. Choose OSM-WMS item from the load profiles ComboBox widget
4. Hit Connect button
5. From the tree list of layers choose some layer e.g. OpenStreetMap WMS - by terrestris
6. Hit Add layer button 
7.  From the Layers pane choose added web service layer OpenStreetMap WMS - by terrestris and by right mouse click invoke layer menu and choose Save web service layer menu item
8. See error

```
Traceback (most recent call last):
  File "/usr/lib64/grass84/gui/wxpython/lmgr/layertree.py",
line 862, in OnSaveWs

parent=self, layer=mapLayer, giface=self._gifaceForDisplay
AttributeError
:
'LayerTree' object has no attribute '_gifaceForDisplay'
```

**Expected behavior**
Saving web service layer as raster map should work.

**System description (please complete the following information):**

- Operating System: all
- GRASS GIS version: 8.4.0dev, 8.3, 8.2

2023-07-27 15:24 UTC, wenzeslaus requested changes
This looks wrong. It is accessing a private attribute of self.mapdisplay. The "GRASS interface" references are meant to be shared to objects you create when appropriate, but not the other way around. `self._giface` like on line 871 would be how the code usually looks like.

2023-07-27 18:32 UTC, tmszi commented
> This looks wrong. It is accessing a private attribute of self.mapdisplay. The "GRASS interface" references are meant to be shared to objects you create when appropriate, but not the other way around. `self._giface` like on line 871 would be how the code usually looks like.

Yes I know about it. Original arg `self._gifaceForDisplay` point to `LayerManagerGrassInterfaceForMapDisplay` class instance which is not avilable as private atribute for `LayerTree` class instance.  `self._giface` atribute point to `LayerManagerGrassInterface` class instance. 

Should I initialize a new `LayerManagerGrassInterfaceForMapDisplay` class instance or use existed `self._giface` atrib as save web service layer class `giface` param arg?

2023-07-27 20:28 UTC, petrasovaa commented
I pushed another solution to this, which seems to be more correct, but I tested it just briefly. For some reason, the PR right now doesn't show the new commit, so I am not sure what's going on.

2023-07-27 20:36 UTC, petrasovaa commented
This is probably a more correct solution, but I did just brief testing.

2023-07-28 01:51 UTC, wenzeslaus approved these changes
The callback is actually a factory method so in a sense it is similar to constructor. In the context of giface concept, constructors should generally get the right giface rather than try to create it themselves.  This moves creation of giface out of the callback and adds giface as its parameter, so it looks like the right solution. It also removes the duplicate code between the two callbacks which is nice and usually a good sign.

2023-08-01 03:12 UTC, merged