lib/parser: Use project for G_OPT_M_LOCATION
OSGeo/grass pull request #3130
Opened 2023-08-16 01:33 UTC by wenzeslaus

Standard option G_OPT_M_LOCATION which creates option named location now creates option named location. Each module using G_OPT_M_LOCATION without further modifications has its own entry in in the renamed options file for backwards compatibility.

New usage of _g.mapset_:

```
> g.mapset project=nc_basic_spm_grass7 mapset=user1
```

Still works:

```
> g.mapset location=nc_spm_08_grass7 mapset=user1
```

The latter produces a warning:

```
WARNING: Please update the usage of <g.mapset>: option <location> has been
         renamed to <project>
```

`g.mapset --h`:

```
Changes/reports current mapset.

Usage:
 g.mapset [-clp] mapset=name [project=name] [dbase=path] [--overwrite]
   [--help] [--verbose] [--quiet] [--ui]

Flags:
  -c   Create mapset if it doesn't exist
  -l   List available mapsets and exit
  -p   Print current mapset and exit

Parameters:
   mapset   Name of mapset (default: current search path)
  project   Project (location) name
    dbase   GRASS GIS database directory
```

This applies to:

* g.mapset
* r.proj
* i.ortho.elev
* g.download.location
* v.proj

2023-09-22 15:36 UTC, wenzeslaus commented
Yes. That fits with the general plan of adding "project" to the API and then gradually removing usage of "location" internally.

2024-02-14 20:31 UTC, cmbarton requested changes
Note the inconsistencies in how the terms Mapset and Location are written in this and other places: mapset, MAPSET, and Mapset. Since we are changing terminology, this is a good opportunity to standardize how these important terms are written. 

As suggested in #2993 and other places, I suggest that we capitalize the first letter and use lower case for the rest of the letters in all descriptions, labels, and documentation--i.e., Mapset and Project--wherever possible. This reduces confusion when people read about these important terms. 

For command-line arguments, I suggest keeping everything in lower case letters of course.

2024-03-16 03:18 UTC, wenzeslaus commented on lib/gis/renamed_options
> +v.proj|location:project
Usage updated in grass.jupyter and elsewhere.

2024-03-16 03:19 UTC, wenzeslaus commented on raster/r.proj/r.proj.html
> -r.proj input=elevation location=ll_wgs84 mapset=user1 -p
The page is long and has a lot of occurrences of location. Perhaps better handled separately from the change in code and usage.

2024-03-18 15:47 UTC, petrasovaa approved these changes

2024-03-22 17:42 UTC, merged