i.ortho.target: Rename location and mapset options to target
OSGeo/grass pull request #3131
Opened 2023-08-17 00:58 UTC by wenzeslaus

i.ortho.target has option target_location and mapset_location. This renames them to target_project and target_mapset, so the new names are consistent. While mapsets are in locations (projects), there seems to be no reason for the word location in mapset_location because it is G_OPT_M_MAPSET.

This also includes change for g.gui.image2target which uses G_OPT_M_LOCATION with a custom name target_location, now renamed target_project. Both old and new names are consistent with target_project in i.ortho.target.

2024-02-14 20:26 UTC, cmbarton requested changes
For consistency with my suggestion for #2993, I again suggest that the word "Project" be capitalized in the label and description. It does not need to be capitalized in the key (i.e., command argument)

2024-03-12 17:54 UTC, petrasovaa requested changes
The manual pages contain "location" as well.

2024-03-12 17:55 UTC, petrasovaa commented on imagery/i.ortho.photo/i.ortho.target/main.c
> +        _("Name of target location (project) for ortho-rectification");
```suggestion
        _("Name of target project (location) for ortho-rectification");
```

2024-03-22 15:37 UTC, petrasovaa submitted a review, later dismissed

2024-03-22 17:48 UTC, petrasovaa approved these changes

2024-03-22 21:42 UTC, merged