[WIP] Msvc void arithmetic
OSGeo/grass pull request #354
Opened 2020-02-18 00:04 UTC by rkanavath

To be merged after https://github.com/OSGeo/grass/pull/353

2025-02-19 16:40 UTC, wenzeslaus commented
Was this addressed somewhere? I don't know. Please, close if you know the PR where this was fixed. Otherwise, I suggest closing this when CMake build works on Windows.

2025-04-06 17:36 UTC, echoix requested changes
I manually compared what this PR was adding on top of the chain of PRs. The previous PR stops at af03bf1d58faeb60cccf2fb718dfa47059bb0af0, so this PR is really only one commit, ceb1d12753ab2b6c31bf068868c1ce7623c714b6.

Most of the changes for r.in.lidar aren't present on main yet, but the ones for lib/raster3d/mask.c might have already been fixed, as a cast to `(char *)` is now used, instead of `(int*)` as suggested in this PR. The base of the PR didn't have any cast.

2025-04-06 17:36 UTC, echoix commented on raster/r.in.lidar/main.c
> +                Rast_get_row(base_raster, (double*)base_array + ((size_t) row * cols * Rast_cell_size(base_raster_data_type)), row, base_raster_data_type);
The current code on main doesn't include a cast to void. It has been reformatted to this though:
```c
if (base_array) {
            G_debug(2, "filling base raster array");
            for (row = 0; row < rows; row++) {
                Rast_get_row(base_raster,
                             base_array +
                                 ((size_t)row * cols *
                                  Rast_cell_size(base_raster_data_type)),
                             row, base_raster_data_type);
            }
        }
```

2025-04-06 17:36 UTC, echoix commented on raster/r.in.lidar/point_binning.c
> +        sumsq = Rast_get_d_value((DCELL*)sumsq_array + offset, rtype);
Not present on main

2025-04-06 17:36 UTC, echoix commented on raster/r.in.lidar/point_binning.c
> +        if (Rast_is_null_value((CELL*)index_array + n_offset, CELL_TYPE))      /* no points in cell */
Not included in main yet

2025-04-06 17:36 UTC, echoix commented on raster/r.in.lidar/point_binning.c
> +            head_id = Rast_get_c_value((CELL*)index_array + n_offset, CELL_TYPE);
Not included in main yet

2025-04-06 17:36 UTC, echoix commented on raster/r.in.lidar/point_binning.c
> +        if (Rast_is_null_value((CELL*)index_array + n_offset, CELL_TYPE))      /* no points in cell */
Not included in main yet

2025-04-06 17:36 UTC, echoix commented on raster/r.in.lidar/point_binning.c
> +            head_id = Rast_get_c_value((CELL*)index_array + n_offset, CELL_TYPE);
Not included in main yet

2025-04-06 17:36 UTC, echoix commented on raster/r.in.lidar/point_binning.c
> +        if (Rast_is_null_value((CELL*)index_array + n_offset, CELL_TYPE))      /* no points in cell */
Not included in main yet

2025-04-06 17:36 UTC, echoix commented on raster/r.in.lidar/point_binning.c
> +            head_id = Rast_get_c_value((CELL*)index_array + n_offset, CELL_TYPE);
Not included in main yet

2025-04-06 17:36 UTC, echoix commented on raster/r.in.lidar/point_binning.c
> +        if (Rast_is_null_value((CELL*)index_array + n_offset, CELL_TYPE))      /* no points in cell */
Not included in main yet

2025-04-06 17:36 UTC, echoix commented on raster/r.in.lidar/point_binning.c
> +            head_id = Rast_get_c_value((CELL*)index_array + n_offset, CELL_TYPE);
Not included in main yet

2025-04-06 17:36 UTC, echoix commented on raster/r.in.lidar/point_binning.c
> +			(CELL*)point_binning->n_array +
Not included in main yet

2025-04-06 17:36 UTC, echoix commented on raster/r.in.lidar/point_binning.c
> +			(CELL*)point_binning->min_array +
Not included in main yet

2025-04-06 17:36 UTC, echoix commented on raster/r.in.lidar/point_binning.c
> +			(CELL*)point_binning->max_array +
Not included in main yet

2025-04-06 17:36 UTC, echoix commented on raster/r.in.lidar/point_binning.c
> +			(CELL*)point_binning->sum_array +
Not included in main yet

2025-04-06 17:36 UTC, echoix commented on raster/r.in.lidar/point_binning.c
> +                Rast_get_d_value((DCELL*)point_binning->min_array + offset, rtype);
Not included in main yet

2025-04-06 17:36 UTC, echoix commented on raster/r.in.lidar/point_binning.c
> +                Rast_get_d_value((DCELL*)point_binning->max_array + offset, rtype);
Not included in main yet

2025-04-06 17:36 UTC, echoix commented on raster/r.in.lidar/point_binning.c
> +            int n = Rast_get_c_value((CELL*)point_binning->n_array + n_offset,
Not included in main yet

2025-04-06 17:36 UTC, echoix commented on raster/r.in.lidar/point_binning.c
> +                Rast_get_d_value((DCELL*)point_binning->sum_array + offset, rtype);
Not included in main yet

2025-04-06 17:36 UTC, echoix commented on raster/r.in.lidar/point_binning.c
> +            int n = Rast_get_c_value((CELL*)point_binning->n_array + n_offset,
Not included in main yet

2025-04-06 17:36 UTC, echoix commented on raster/r.in.lidar/point_binning.c
> +                Rast_get_d_value((DCELL*)point_binning->x_array + offset, rtype);
Not included in main yet

2025-04-06 17:36 UTC, echoix commented on raster/r.in.lidar/point_binning.c
> +                Rast_get_d_value((DCELL*)point_binning->y_array + offset, rtype);
Not included in main yet

2025-04-06 17:36 UTC, echoix commented on raster/r.in.lidar/point_binning.c
> +                Rast_get_d_value((DCELL*)point_binning->sum_array + offset, rtype);
Not included in main yet

2025-04-06 17:36 UTC, echoix commented on raster/r.in.lidar/point_binning.c
> +            /* We are not writing any categories. They are not neededsb
ignore

2025-04-06 19:40 UTC, closed without merging

2025-04-06 19:40 UTC, echoix commented
Replaced by https://github.com/OSGeo/grass/pull/5509