lib raster: fixed security vulnerabilities and weaknesses
OSGeo/grass pull request #3549
Opened 2024-04-01 15:23 UTC by jadenabrams100

This PR fixes three vulnerabilities/weaknesses found with older scans of Coverity. 

Issue 1208372 in error.c concerns an unbounded read of an environment variable into memory. An attacker could overwrite the environment variable that is accessed by G__home() and exploit it to overflow the buf array.

Issue 1501330 in mapset_msc.c concerns writing into an array that is not null terminated. If the path variable was not null terminated, the write could fill the whole array with data without a null terminator, causing trouble down the line.

Issue 1207344 in raster/r.gwflow/main.c concerns a constant variable guarding dead code. This is not exactly a security vulnerability, but is a code quality issue I was able to easily fix.

2024-04-01 17:19 UTC, marisn requested changes

2024-04-01 17:19 UTC, marisn commented on lib/gis/mapset_msc.c
> +    path[GPATH_MAX] = 0;
Although I do not think here not-null terminated p_path can reach this function, it wouldn't harm either.

Please change from 0 to '\0' to make your intent clearer.

2024-04-02 05:51 UTC, marisn submitted a review, later dismissed

2024-04-02 08:03 UTC, nilason requested changes
I added some suggestion. In general it is advisable to constrain buffer sizes defined by constants like `GPATH_MAX` to include null terminator (i.e. not to increase it with 1).

2024-04-03 19:38 UTC, jadenabrams100 commented on lib/gis/error.c
> +        char buf[GPATH_MAX + 1];
Ok I just added that in. Thank you!

2024-04-03 19:38 UTC, jadenabrams100 commented on lib/gis/mapset_msc.c
> +    char path[GPATH_MAX + 1], *p;
Ok I have added that in. Thank you!

2024-04-03 20:04 UTC, jadenabrams100 commented
I am not certain why the MacOS job failed.

2024-04-03 20:33 UTC, nilason commented on lib/gis/mapset_msc.c
> +    path[GPATH_MAX] = '\0';
You should delete line 189.

2024-04-03 23:02 UTC, echoix commented
> I am not certain why the MacOS job failed.

Just to make sure I made a rerun of the job, and still failed early.

The earliest possible error that I was only able to spot was the linker not being able to link libgrass, but didn’t find another more descriptive error in the compilation.

2024-04-03 23:11 UTC, echoix commented
I'm surprised that another Clang-based job didn't fail. I only see that Travis builds with gcc and clang, but on Ubuntu focal. I thought we had more clang jobs than that.

2024-04-04 07:45 UTC, nilason commented
> I am not certain why the MacOS job failed.

In the CI log you can find the reason:
```
mapset_msc.c:189:5: error: array index 4096 is past the end of the array (that has type 'char[4096]') [-Werror,-Warray-bounds]
    path[GPATH_MAX] = '\0';
    ^    ~~~~~~~~~
mapset_msc.c:186:5: note: array 'path' declared here
    char path[GPATH_MAX] = {'\0'};
    ^
1 error generated.
```

which is the same issue as the CodeQL reports.

2024-04-04 07:51 UTC, nilason commented
> I'm surprised that another Clang-based job didn't fail. I only see that Travis builds with gcc and clang, but on Ubuntu focal. I thought we had more clang jobs than that.

The macOS CI is built with `-Wall -Wextra -Wpedantic -Werror`, which makes the difference. The gcc CI's have the same build flags, but gcc has different set of warnings activated with those compared to clang.

2024-04-05 18:17 UTC, jadenabrams100 commented on lib/gis/mapset_msc.c
> +    path[GPATH_MAX] = '\0';
I do not know how that slipped past my mind, I will get that fixed my apologies!

2024-04-06 15:10 UTC, echoix commented
Is this ready now that CI passes?

2024-04-06 16:09 UTC, jadenabrams100 commented
> Is this ready now that CI passes?

Yes, it is ready now.

2024-04-07 12:59 UTC, nilason approved these changes

2024-04-07 12:59 UTC, merged