PDAL: use NoFileWriter class for PDAL > 2.7.0 (fixes #3552)
OSGeo/grass pull request #3567
Opened 2024-04-07 09:15 UTC by marisn

Starting from PDAL 2.7.0 filename is mandatory for Writer class, but there is a NoFileWriter class that maintains old behaviour. https://github.com/PDAL/PDAL/pull/4342

2024-04-07 11:40 UTC, nilason requested changes
Looks good to me, only one minor suggestion.

2024-04-07 11:40 UTC, nilason commented on include/grass/config.h.in
> +/* Define to 1 if PDAL >2.7.0 Writters should be used */
This would have been the result of `autoheader`:

```suggestion
/* Define to 1 if PDAL NoFilenameWriter is present. */
```

2024-04-07 14:34 UTC, nilason approved these changes
Great, thanks!

2024-04-07 15:45 UTC, merged

2024-04-12 07:52 UTC, landam commented
@marisn Are you planning backport to 8.3 in order to close [#3552](https://github.com/OSGeo/grass/issues/3552) ?