grassTask.get_param(): full match also for strings
OSGeo/grass pull request #3582
Opened 2024-04-12 08:42 UTC by landam

`grassTask.get_param()` does not perform full match on string data type, see https://github.com/OSGeo/grass/blob/main/python/grass/script/task.py#L151

This may lead to buggy behaviour as explained below.

Sample code:

```py
from grass.script.task import grassTask

print(grassTask("r.mapcalc.simple").get_param('e')['name'])
```

returns `expression` instead of `e`.

2024-04-12 23:13 UTC, echoix commented
I don't understand enough this part of the code to know what's going on.

Could the broken behaviour be written in a simple unit test so we would see it fail and then fixed? Either for grassTask or mapcalc.

Something like:
```python
import pytest
from grass.script.task import grassTask as gtask

def test_mapcalc_simple_e_name():
    gt = gtask("r.mapcalc.simple")
    assert gt.get_param('e')['name'] == 'e'

def test_mapcalc_simple_expession_name():
    gt = gtask("r.mapcalc.simple")
    assert gt.get_param('expression')['name'] == 'expression'

```

I just wrote it on the fly, there might be formatting errors

2024-04-13 02:03 UTC, echoix commented
Ok, I had the chance to run the equivalent test file in my branch. I purposely made it based on my set of branches that are behind the main repo, but advanced on code coverage and better pytest reporting.

So before the fix of this PR:
https://github.com/echoix/grass/pull/72

And after applying the fix of this PR:
https://github.com/echoix/grass/pull/73

The test fails before and after.
I think I might not understood your example correctly then, as we see from these traces

https://github.com/echoix/grass/actions/runs/8670103706/job/23777706024?pr=72#step:13:182

https://github.com/echoix/grass/actions/runs/8670117007/job/23777729558?pr=73#step:13:179

![image](https://github.com/OSGeo/grass/assets/27212526/eb0989d7-a2b1-47d3-ae33-419efcee8835)
![image](https://github.com/OSGeo/grass/assets/27212526/9a704f78-566e-45a5-8f2f-8105f9e5b4ce)

2024-04-18 01:00 UTC, wenzeslaus requested changes
This looks like another case where our Python code is trying to mimic what is happening in the parser, but it fails to account for all the cases.

However, given the confusion around it, it would be better to have a test before moving forward here.

2024-05-10 17:05 UTC, wenzeslaus submitted a review, later dismissed
After the discussion during PSC meeting, it seems to me that there is was not strong reason in the past to have these lines there. It can always fallback to the full match now and before. So, we can behave like these lines were never there.

I don't have an opinion on how far this should be backported except that the only supported release series is 8.3 at this point (by us a the project; us as individuals contributors can pursue fixing and release other versions).

Let's proceed.

2024-05-10 17:12 UTC, wenzeslaus commented
> The test fails before and after.

@landam's example works for me:

```python
grass-dev --tmp-project XY --exec python -c 'from grass.script.task import grassTask; print(grassTask("r.mapcalc.simple").get_param("e")["name"])'
```

Having it in the code, it would be nice to have.

2024-05-11 15:20 UTC, landam commented
> ```python
> grass-dev --tmp-project XY --exec python -c 'from grass.script.task import grassTask; print(grassTask("r.mapcalc.simple").get_param("e")["name"])'
> ```

Before:

```
./bin.x86_64-pc-linux-gnu/grass --tmp-project XY --exec python3 -c 'from grass.script.task import grassTask; print(grassTask("r.mapcalc.simple").get_param("e")["name"])'
expression
```

-> wrong match

After:

```
./bin.x86_64-pc-linux-gnu/grass --tmp-project XY --exec python3 -c 'from grass.script.task import grassTask; print(grassTask("r.mapcalc.simple").get_param("e")["name"])'
e
```

-> correct match

> Having it in the code would be nice to have.

Truly to say I am not sure what do you mean by this statement. Can you clarify it?

2024-05-11 15:33 UTC, echoix commented
> > ```python
> 
> > grass-dev --tmp-project XY --exec python -c 'from grass.script.task import grassTask; print(grassTask("r.mapcalc.simple").get_param("e")["name"])'
> 
> > ```
> 
> 
> 
> Before:
> 
> 
> 
> ```
> 
> ./bin.x86_64-pc-linux-gnu/grass --tmp-project XY --exec python3 -c 'from grass.script.task import grassTask; print(grassTask("r.mapcalc.simple").get_param("e")["name"])'
> 
> expression
> 
> ```
> 
> 
> 
> -> wrong match
> 
> 
> 
> After:
> 
> 
> 
> ```
> 
> ./bin.x86_64-pc-linux-gnu/grass --tmp-project XY --exec python3 -c 'from grass.script.task import grassTask; print(grassTask("r.mapcalc.simple").get_param("e")["name"])'
> 
> e
> 
> ```
> 
> 
> 
> -> correct match
> 
> 
> 
> > Having it in the code would be nice to have.
> 
> 
> 
> Truly to say I am not sure what do you mean by this statement. Can you clarify it?

I assume this means written as a test?

2024-05-11 15:40 UTC, echoix commented on python/grass/script/tests/test_script_task.py
> +import pytest
```suggestion
```

Seems like flake8 doesn't like that I didn't use any fixtures at all finally, so pytest is unused. Would this work?

2024-05-11 16:16 UTC, wenzeslaus commented
Yes, no need to import pytest for a basic pytest test. They don't run as
standalone scripts.

On Sat, May 11, 2024, 11:40 AM Edouard Choinière ***@***.***>
wrote:

> ***@***.**** commented on this pull request.
> ------------------------------
>
> In python/grass/script/tests/test_script_task.py
> <https://github.com/OSGeo/grass/pull/3582#discussion_r1597467163>:
>
> > @@ -0,0 +1,12 @@
> +import pytest
>
> ⬇️ Suggested change
>
> -import pytest
>
> Seems like flake8 doesn't like that I didn't use any fixtures at all
> finally, so pytest is unused. Would this work?
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/OSGeo/grass/pull/3582#pullrequestreview-2051223858>,
> or unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ABJSKZE6LPDG25XNJRJKBBLZBY3W3AVCNFSM6AAAAABGDXNTHGVHI2DSMVQWIX3LMV43YUDVNRWFEZLROVSXG5CSMV3GSZLXHMZDANJRGIZDGOBVHA>
> .
> You are receiving this because your review was requested.Message ID:
> ***@***.***>
>

2024-05-11 16:18 UTC, wenzeslaus commented
Yes, having it written as a test is what I meant to say. Nice to have ==
not required but desirable.

On Sat, May 11, 2024, 11:33 AM Edouard Choinière ***@***.***>
wrote:

> grass-dev --tmp-project XY --exec python -c 'from grass.script.task import
> grassTask; print(grassTask("r.mapcalc.simple").get_param("e")["name"])'
>
> Before:
>
>
> ./bin.x86_64-pc-linux-gnu/grass --tmp-project XY --exec python3 -c 'from grass.script.task import grassTask; print(grassTask("r.mapcalc.simple").get_param("e")["name"])'
>
> expression
>
>
> -> wrong match
>
> After:
>
>
> ./bin.x86_64-pc-linux-gnu/grass --tmp-project XY --exec python3 -c 'from grass.script.task import grassTask; print(grassTask("r.mapcalc.simple").get_param("e")["name"])'
>
> e
>
>
> -> correct match
>
> Having it in the code would be nice to have.
>
> Truly to say I am not sure what do you mean by this statement. Can you
> clarify it?
>
> I assume this means written as a test?
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/OSGeo/grass/pull/3582#issuecomment-2105934327>, or
> unsubscribe
> <https://github.com/notifications/unsubscribe-auth/ABJSKZDECB6XHU3EGRDAHCDZBY25PAVCNFSM6AAAAABGDXNTHGVHI2DSMVQWIX3LMV43OSLTON2WKQ3PNVWWK3TUHMZDCMBVHEZTIMZSG4>
> .
> You are receiving this because your review was requested.Message ID:
> ***@***.***>
>

2024-05-11 17:20 UTC, echoix approved these changes

2024-05-11 18:40 UTC, landam commented
> Yes, having it written as a test is what I meant to say. Nice to have == not required but desirable.

Done by @echoix (thanks).

2024-05-11 20:17 UTC, merged

2024-05-11 21:52 UTC, echoix commented
You were able to merge even with the failed required windows builds?

2024-05-14 15:02 UTC, landam commented
Yes, I bypassed the requirements exceptionally. Failing CI was not related to this PR.