v.db.select: fix escaping SQL columns names with SQL standard double quotes
OSGeo/grass pull request #3614
Opened 2024-04-17 12:03 UTC by tmszi

Fix escaping SQL columns names with SQL standard double quotes if v.db.select module `columns` param arg is used.

[Example](https://github.com/OSGeo/grass/issues/3604#issuecomment-2058805737) for testing purpose.

v.db.select module with `columns` param arg should sucessfully return columns data in the case when column name **order** is DB reserved keyword:

```
GRASS hybas/PERMANENT:~ > v.db.select hybas_lake_eu_lev01_v1c column=cat,order
cat|order
1|0
```

2024-04-17 12:45 UTC, wenzeslaus requested changes
This is a issue in couple places and I'm happy to see this addressed at least here. On the other hand, I'm not sure how the different systems handle quoting. It seems that while standard is a double quote, what is enabled by default and what double quote actually means may differ. More analysis may be required.

The previous implementation was passing the values as is, so one could pass the quoting characters and it would work. This will not work with the current code in this PR.

A test would be really good.

2024-04-17 12:45 UTC, wenzeslaus commented on vector/v.db.select/main.c
> +        char *token = strtok(options.cols->answer, col_sep);
Any opinions on using strtok versus [G_tokenize](https://grass.osgeo.org/programming8/defs_2gis_8h.html#af6abbab981ffd86ea461668f6f5c8310)?

2024-04-17 12:45 UTC, wenzeslaus commented on vector/v.db.select/main.c
> +            token = strtok(NULL, col_sep);
Passing NULL is not clear to me here.

2024-04-17 14:54 UTC, marisn commented
> On the other hand, I'm not sure how the different systems handle quoting. It seems that while standard is a double quote, what is enabled by default and what double quote actually means may differ. More analysis may be required.

Most of systems GRASS supports are SQL standards compliant. MySQL compliance is addressed in #3612. This PR also needs an update to documentation – mention that quoting column parameter is not necessary any more.

At the moment only DBF driver is broken – it needs some magick in sqlp.l file (any lex experts reading this?)

2024-04-18 05:56 UTC, tmszi commented on vector/v.db.select/main.c
> +        char *token = strtok(options.cols->answer, col_sep);
Fixed with `G_tokenize()` func.

2024-04-18 06:12 UTC, tmszi commented
> A test would be really good.

Test has been added.

2024-04-19 04:42 UTC, tmszi commented
With this changes another v.dissolve module pytests fails. According my analysis, with automatically enclose column names with double quotes when v.db.select module param `columns` and `group` is used, it will require much more code changes (handle SQL func, module JSON output format) and increase complexity of code.

If v.db.select require to use `columns` or `group` param with column name which is DB backend reserved keyword it will be much easier enclose this column with double quotes on the param arg level as before.

2024-04-19 04:42 UTC, closed without merging