r.horizon: always include distance output in JSON output
OSGeo/grass pull request #3768
Opened 2024-06-04 15:57 UTC by petrasovaa

Given the [discussion](https://github.com/OSGeo/grass/pull/3744#issuecomment-2135488969) about what should be part of JSON output, I changed the behavior to include the distance whether or not the -l flag is used. There is no computational reason not to.

2024-06-04 16:01 UTC, echoix submitted a review, later dismissed

2024-06-05 19:41 UTC, wenzeslaus requested changes

2024-06-05 19:41 UTC, wenzeslaus commented on raster/r.horizon/testsuite/test_r_horizon.py
> +        stdout[0].pop("horizon_distance", None)
If I understand correctly, reverting the code change would still keep the test as passing. In other words, this does not test the expectations. We should test that distance is emitted by the tool.

2024-06-07 14:02 UTC, wenzeslaus approved these changes

2024-06-07 15:05 UTC, merged