r.univar: add JSON support
OSGeo/grass pull request #3783
Opened 2024-06-07 12:34 UTC by kritibirda26

Use parson to add json output format support to the r.univar module.

Expected JSON schema:

At the root is an array, each element of which has the stats for a given zone. The percentile option allows the user to request specific percentiles which are written for each zone object as `percentile_%d` keys.

```
[
    {
        "zone_number": <int>,
        "zone_category": <string>,
        "n": <int>,
        "null_cells": <int>,
        "cells": <int>,
        "min": <double>,
        "max": <double>,
        "range": <double>,
        "mean": <double>,
        "mean_of_abs": <double>,
        "stddev": <double>,
        "variance": <double>,
        "coeff_var": <double>,
        "sum": <double>,
        "first_quartile": <double>,
        "median": <double>,
        "third_quartile": <double>,
        "percentile_98": <double>
    }
]
```

2024-06-07 13:16 UTC, wenzeslaus commented
Can you please compare this schema to what db.univar generates? Maybe they don't need to be the same, but if they are not, we need to have a good reason for that.

2024-06-07 14:58 UTC, echoix commented
> @wenzeslaus Can you please point me to the db.univar module, I am unable to find it.

https://github.com/OSGeo/grass/tree/f13b37931af919be04fa14f392a1f9ea9aa183fd/scripts/db.univar

2024-07-01 17:40 UTC, cwhite911 requested changes
Update json output and tests to match `v.univar`.

2024-07-02 12:51 UTC, kritibirda26 commented
@cwhite911 updated.

2024-07-02 13:03 UTC, nilason requested changes

2024-07-02 13:03 UTC, nilason commented on raster/r.univar/stats.c
>                      sprintf(buf, "%.15g", stats[z].perc[i]);
Even if not introduced by this PR, you might change `sprintf` to the more safer `snprintf`:
```suggestion
                    snprintf(buf, sizeof(buf), "%.15g", stats[z].perc[i]);
```

2024-07-02 13:03 UTC, nilason commented on raster/r.univar/stats.c
> +                    char buf[24], buf2[36];
This causes the CI runners to fail.

2024-07-02 14:32 UTC, nilason approved these changes

2024-07-03 12:12 UTC, cwhite911 approved these changes
@kritibirda26 nice work!

2024-07-03 18:32 UTC, nilason approved these changes
Code looks good to me, I haven't tested though.

2024-07-03 18:58 UTC, merged