Adds basic unit tests to v.out.ogr
OSGeo/grass pull request #3848
Opened 2024-06-16 12:09 UTC by ldesousa

2024-06-17 14:58 UTC, wenzeslaus requested changes
Just a detail. Pylint would report the same.

2024-06-17 14:58 UTC, wenzeslaus commented on vector/v.out.ogr/testsuite/test_v_out_ogr.py
> +            output="%s.gpkg" % self.test_map,
```suggestion
            output=f"{self.test_map}.gpkg"
```

Same also elsewhere.

2024-06-18 14:53 UTC, wenzeslaus reviewed
Please, see the other PR for comments on comments.

2024-07-03 12:30 UTC, echoix reviewed
A ruff fix suggestion

2024-07-03 12:30 UTC, echoix commented on vector/v.out.ogr/testsuite/test_v_out_ogr.py
> +        for p in Path(".").glob(f"{self.test_map}*"):
```suggestion
        for p in Path().glob(f"{self.test_map}*"):
```

2024-07-31 16:44 UTC, echoix commented
I'm about to approve it, but what were the comments of the other PR that Vaclav was referring to? They have been addressed?

2024-07-31 16:44 UTC, echoix submitted a review, later dismissed

2024-07-31 17:08 UTC, wenzeslaus commented on vector/v.out.ogr/testsuite/test_v_out_ogr.py
> +        """!Remove the temporary region"""
```suggestion
        """Remove the temporary region"""
```

2024-07-31 17:10 UTC, wenzeslaus approved these changes
This looks good and the comments look good. Thank you for the updates!

2024-07-31 18:58 UTC, merged