r.profile: add JSON support
OSGeo/grass pull request #3872
Opened 2024-06-17 14:41 UTC by kritibirda26

Use parson to add json output format support to the r.profile module.

The output format is as follows:

```json
[
    {
        "easting": <float>,
        "northing": <float>,
        "distance": <float>,
        "elevation": <float>,
        "red": <int>,
        "green": <int>,
        "blue": <int>
    },
    {
        "easting": <float>,
        "northing": <float>,
        "distance": <float>,
        "elevation": <float>,
        "red": <int>,
        "green": <int>,
        "blue": <int>
    },
...
]
```

Note that the `elevation` field is the name of the input and `red`, `green`, `blue`  fields are only included if the `colors` flag is specified.

2024-06-26 22:09 UTC, cwhite911 requested changes

2024-06-29 19:28 UTC, kritibirda26 commented on raster/r.profile/read_rast.c
I tried to do that but I get a double free error, dcell is marked as static and hence cannot be freed immediately at the end of the function as read_rast can be called inside a loop. Should I make dcell non-static or do you have any other suggestions on how to fix the issue?

2024-06-29 19:56 UTC, kritibirda26 commented on raster/r.profile/read_rast.c
> +        json_object_set_number(object, "easting", east);
Done

2024-06-29 19:56 UTC, kritibirda26 commented on raster/r.profile/r.profile.html
> +
Done

2024-07-01 16:49 UTC, cwhite911 commented on raster/r.profile/read_rast.c
@kritibirda26  just focus on finishing up the json part. If their is a memory leak here we can open a new issue to address that separately.

2024-07-01 17:17 UTC, cwhite911 approved these changes
Looks good!

2024-07-02 09:34 UTC, echoix approved these changes
Proxying @cwhite911's approval

2024-07-02 09:54 UTC, merged