v.distance: add json support
OSGeo/grass pull request #3942
Opened 2024-06-29 16:45 UTC by kritibirda26

Using parson, add JSON support to v.distance module.

The output looks like as follows:

```json
[
    {
        "from_cat": 1,
        "to_cat": 33,
        "distances": [
            {
                "value": 54371.188688694157,
                "name": "dist"
            },
            {
                "value": "Zebulon",
                "name": "to_attr"
            }
        ]
    },
    {
        "from_cat": 8,
        "to_cat": 18,
        "distances": [
            {
                "value": 284.67149902717813,
                "name": "dist"
            },
            {
                "value": "RFD #14",
                "name": "to_attr"
            }
        ]
    }
]
```

I will add tests and update documentation once the JSON format is finalized.

2024-07-11 21:49 UTC, cwhite911 requested changes
@kritibirda26 please add tests.

2024-08-06 09:20 UTC, kritibirda26 commented
@cwhite911 the pr is ready for review.

2024-08-11 17:11 UTC, cwhite911 requested changes

2024-08-11 17:11 UTC, cwhite911 commented on vector/v.distance/main.c
> +            case JSON:
Let's add a json representation for print as matrix `-s` flag. Maybe something like this schema, but I'm open to suggestions.

```json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "title": "DistanceMatrix",
  "description": "A matrix representing distances between points",
  "type": "array",
  "items": {
    "type": "array",
    "items": {
      "type": "number"
    }
  }
}
```

2024-08-11 17:11 UTC, cwhite911 commented on vector/v.distance/testsuite/test_v_distance.py
Add test for distance matrix.

```bash
v.distance -pas from=hospitals to=hospitals upload=dist format=json
```

2024-08-12 13:16 UTC, kritibirda26 commented on vector/v.distance/print.c
> +                            /* TODO: formatting datetime */
This is left over from the plain print case which also doesn't support datetime at the moment, I think it we can address it later together with plain case.

2025-01-17 17:02 UTC, cwhite911 approved these changes
Nice job @kritibirda26!

2025-01-20 19:03 UTC, echoix approved these changes

2025-01-23 14:23 UTC, echoix commented
@cwhite911 the PR will automatically merge once all conditions are met, that means that there's only open conversations remaining

2025-01-23 16:49 UTC, cwhite911 commented
> @cwhite911 the PR will automatically merge once all conditions are met, that means that there's only open conversations remaining

@echoix I don't see a button to resolve conversations anymore. Did a setting recently get changed?

2025-01-23 16:53 UTC, echoix commented
Oh, maybe you don't even have triage access? It's surprising.. 

Comment like done on them, to make sure we don't forget some, and I'll close them

cc @neteler can you take a look at what level he should be having (especially if he was mentoring students, and couldn't approve them himself)

2025-01-23 17:51 UTC, cwhite911 commented on vector/v.distance/main.c
> +            case JSON:
Done

2025-01-23 17:51 UTC, cwhite911 commented on vector/v.distance/print.c
> +                            /* TODO: formatting datetime */
Done

2025-01-23 17:54 UTC, cwhite911 commented on vector/v.distance/testsuite/test_v_distance.py
Done. We should still include more tests here, but I think we should make a new PR for them.

2025-01-23 17:55 UTC, merged

2025-01-23 17:55 UTC, echoix commented
Done!

2025-01-24 16:29 UTC, petrasovaa commented
This triggered:
```
*** CID 1590732:  Memory - illegal accesses  (UNINIT)
/vector/v.distance/print.c: 109 in print_upload()
103                         }
104                         else {
105                             json_object_set_null(relation_object, "value");
106                         }
107                         break;
108                     }
>>>     CID 1590732:  Memory - illegal accesses  (UNINIT)
>>>     Using uninitialized value "name" when calling "json_object_set_string".
109                     json_object_set_string(relation_object, "name", name);
110                     json_array_append_value(relations, relation_value);
111                     break;
112                 case PLAIN:
113                     switch (Upload[j].upload) {
114                     case CAT:
```