v.to.db: add JSON support
OSGeo/grass pull request #4036
Opened 2024-07-11 19:17 UTC by kritibirda26

Add JSON output support to v.to.db module. The output looks like as follows:

```json
{
    "totals": {
        "area": 2219442027.2203522
    },
    "records": [
        {
            "category": 1,
            "area": 24375323.127803534
        },
        {
            "category": 2,
            "area": 2938964.3204806102
        },
        {
            "category": 3,
            "area": 50536154.294107705
        }
    ],
...
}
```

2024-07-25 19:26 UTC, kritibirda26 commented
@cwhite911 Hi! Can you please review this PR? I would like to use the JSON format added in the v.report module's JSON implementation to keep the implementation simple.

2024-07-25 20:35 UTC, nilason commented on vector/v.to.db/report.c
> +        }
```suggestion
        }
        break;
```

may perhaps fix the failed runner.

2024-07-27 15:34 UTC, cwhite911 commented
> @cwhite911 Hi! Can you please review this PR? I would like to use the JSON format added here in the v.report module's JSON implementation to keep the implementation simple.

@kritibirda26 the schema looks good to me, however I'm debating if we should add the measurement unit to the root object.

2024-07-27 15:49 UTC, echoix commented
If it's documented for now, it won't be breaking to add it at a later time if needed. So if you can't decide after thinking about it for a while, there's a way to keep the PR going.

2024-07-27 17:42 UTC, cwhite911 requested changes
@kritibirda26 This is looking good. Please add test for all of the possible output schemas and update the docs to make it clear that output format only works when the -p flag is set.

2024-08-01 07:28 UTC, kritibirda26 commented
@cwhite911 can you please take another look at this PR?

2024-08-01 19:05 UTC, cwhite911 commented
@kritibirda26 Please add additional unit tests to capture the all of the response data types (point, line, polygon, 3d vectors, mixed with the **options**: `cat, area, compact, fd, perimeter, length, count, coor, start, end, sides, query, slope, sinuous, azimuth, bbox`.

Let's also add the measurement unit to the root json object.

2024-08-02 05:10 UTC, kritibirda26 commented
@cwhite911 Should there be at least one test covering each type and each option? asking because it doesn't seem possible to provide multiple options or types to `v.to.db` at once.

2024-08-13 17:04 UTC, cwhite911 commented
> @cwhite911 Should there be at least one test covering each type and each option? asking because it doesn't seem possible to provide multiple options or types to `v.to.db` at once.

Yes, we should add a test to make sure each key value pair is correctly generated for the option.

2024-08-20 15:48 UTC, kritibirda26 commented
@cwhite911 I have added more tests and measurement units to the root of the object. Can you please suggest which maps/commands to use to test query, azimuth, sinuousity and slope?

2024-08-20 16:21 UTC, echoix requested changes

2024-08-20 16:21 UTC, echoix commented on vector/v.to.db/report.c
Also make sure to avoid the uninitialized warning like the other module.

2024-08-26 19:31 UTC, cwhite911 requested changes
The azimuth is calculated from a line feature. I suggest using the `majorroads` layer for the test.

## Azimuth

```
v.to.db -p map=roadsmajor@PERMANENT option=azimuth units=radians format=json
```

```
v.to.db -p map=roadsmajor@PERMANENT option=azimuth units=degrees format=json
```

## Sinuous

```
v.to.db -p map=roadsmajor@PERMANENT option=sinuous format=json
```

## Slope

To test slope I don't think we have a layer in the test dataset the is line feature with z coordinates.

For the test you could create one using `v.to.3d` and then testing that with

```
v.to.db -p map=roadsmajor3d option=slope units=degrees format=json
```

2024-08-26 19:59 UTC, cwhite911 commented on vector/v.to.db/report.c
I'm not sure what you mean here. Will you remind me of the other module?

2024-08-26 22:17 UTC, echoix commented on vector/v.to.db/report.c
ff98e4212640bac95e206771573506a37c8822b7,
Follow the PR, the comment, and if you have access to coverity, the new detection after the PR #4201 was merged.

2024-08-29 06:55 UTC, kritibirda26 commented
@cwhite911, Hi! I have updated the PR with tests for azimuth and sinuous. For slope, I tried to create a 3d map but failed. I also followed other examples of creating a 3d dataset from 2d (from the tests of other modules) but the slope always comes to be 0 in both plain and json mode.

2025-02-11 17:53 UTC, cwhite911 requested changes
@kritibirda26 will you please approve the suggestions I've just added. @echoix your open conversation should be resolved once the changes are  accepted.

2025-02-11 17:53 UTC, cwhite911 commented on vector/v.to.db/report.c
> +    JSON_Object *record, *root_object;
```suggestion
    JSON_Value *records_value = NULL, *record_value = NULL, *root_value = NULL;
    JSON_Array *records_array = NULL;
    JSON_Object *record = NULL, *root_object = NULL;
```

2025-03-20 13:10 UTC, kritibirda26 commented on vector/v.to.db/report.c
Done.

2025-05-15 10:12 UTC, echoix commented
Missing to adjust cmakefiles to add json in v.to.db

2025-05-15 21:21 UTC, echoix approved these changes
Approving to remove my previously requested changes. With the new test, 301/329 = 0.914894 and will still work with the lower threshold.

2025-05-16 13:45 UTC, merged