style: Fix dict-index-missing-items (PLC0206)
OSGeo/grass pull request #4138
Opened 2024-08-05 01:15 UTC by echoix

Ruff rule: https://docs.astral.sh/ruff/rules/dict-index-missing-items/

9 instances solved

2024-08-05 01:19 UTC, echoix commented on gui/wxpython/gmodeler/model.py
> +            for b in aid.keys():  # noqa: PLC0206
I was conservative here. I'm not sure using `key, value` would behave when appending to `value` during iteration.

2024-08-05 01:19 UTC, echoix commented on gui/wxpython/datacatalog/tree.py
> +                self._giface.lmgr.AddMaps(list(reversed(value)), ltype, True)
I'm open to a better name than `value`, I didn't manage to infer from context.

2024-08-05 01:19 UTC, echoix commented on python/grass/temporal/temporal_granularity.py
> +            for time_unit in granularity_units.keys():  # noqa: PLC0206
Even once fixed, the rule still triggered.

2024-08-05 01:19 UTC, echoix commented on python/grass/temporal/temporal_granularity.py
> +            for time_unit in granularity_units.keys():  # noqa: PLC0206
Here also, even once fixed, the rule still triggered.

2024-08-05 01:19 UTC, echoix commented on scripts/i.pansharpen/i.pansharpen.py
> +        for j in stats_dict.keys():  # noqa: PLC0206
Rule still triggered after fixing.

2024-08-05 01:19 UTC, echoix commented on scripts/r.pack/r.pack.py
> +            for f, value in vrt_files.keys():
I'm open to a better name than `value`, I didn't manage to infer from context.

2024-08-07 11:10 UTC, ninsbl requested changes
I think there is one glitch.

In general I see you explicitly call `.keys()` when you loop over dicts. Should that be the standard?

Weird that ruff complains despite your fixes. Is there probably an issue with ruff?

2024-08-07 11:18 UTC, echoix commented
> I think there is one glitch.
> 
> 
> 
> In general I see you explicitly call `.keys()` when you loop over dicts. Should that be the standard?

There are three ways (and one more): `.keys()` for only returning the dict's keys, `.values()` for only returning the dict's values, and `.items()` to return a tuple of both. Using the appropriate one when not using both of them is the correct thing to do.

(The last one is without anything, that returns the keys if I remember right, but it's not as obvious for reading. It's more useful for `in` checks.)



> 
> Weird that ruff complains despite your fixes. Is there probably an issue with ruff?
Probably I should be reporting it and getting it fixed in a week or so. That one is a preview rule I think.

2024-08-07 12:03 UTC, ninsbl approved these changes

2024-08-07 16:04 UTC, echoix commented
@ninsbl I assume you were fine with the comments I added as explanations, so I’ll resolve them

2024-08-07 16:06 UTC, merged