g.download.location: print target path in error message
OSGeo/grass pull request #4155
Opened 2024-08-08 12:33 UTC by neteler

To be less obscure in case the target location directory already exists:

```
ERROR: Location named <nc_spm_full_v2alpha2> already exists, download
       canceled
```

this PR improves the error message to include the path:

```
g.download.location url=https://grass.osgeo.org/sampledata/north_carolina/nc_spm_full_v2alpha2.tar.gz path=$HOME
ERROR: Location named <nc_spm_full_v2alpha2> already exists in
       </home/mneteler/nc_spm_full_v2alpha2>, download canceled
```

This is esp. relevant for scripted usage when the command isn't invoked directly by the user.

In addition, section  of **EXAMPLES** added.

2024-08-08 12:34 UTC, neteler commented
(I came across this issue while locally testing https://github.com/OSGeo/grass-addons/blob/grass8/.github/workflows/test.sh)

2024-08-09 14:04 UTC, wenzeslaus requested changes

2024-08-09 14:04 UTC, wenzeslaus commented on scripts/g.download.location/g.download.location.py
> +                name, destination
With more than one substitution, you need to use keywords. For the message itself, I think "in" suggests it is inside a directory, so you should put there what is in the database variable, not destination. So:

```suggestion
            _("Location named <{name}> already exists in <{directory}>, download canceled").format(
                name=name, directory=database
```

2024-08-09 14:04 UTC, wenzeslaus commented on scripts/g.download.location/g.download.location.html
> +</pre></div>
Given the context and given that you do try to deal with that later anyway, it seems better to me to mention here that it is in an session.

2024-08-13 17:15 UTC, echoix commented
Slightly related, but the same problem: I read the docs of g.download.location the other day, and it seems there isn't a way to either download if missing, or to not fail if the same dataset already exists. 

If it was possible, it would allow for example to use the script test_thorough.sh in the CI, and run it locally multiple times, instead of being able to run it once, then to adapt and only copy the second invocation.

At least this PR improves by showing more info as to where the data already exists.

2024-08-14 13:22 UTC, veroandreo reviewed
NC sample datasets are projects. I'd avoid calling them databases since usually the grassdata folder (a folder of projects) is called database. Also included a suggestion for @wenzeslaus' comment.

2024-08-14 14:51 UTC, neteler commented on scripts/g.download.location/g.download.location.py
> +                "Location named <{name}> already exists in <{directory}>, download canceled"
It corresponds to the name `g.download.location`.

We then might also need to rename the command (which would be API breaking, so only in GRASS GIS 9).

2024-08-19 17:19 UTC, wenzeslaus commented on scripts/g.download.location/g.download.location.py
> +                "Location named <{name}> already exists in <{directory}>, download canceled"
Addressed by #4187.

2024-08-19 22:25 UTC, merged