Update infomanager.py: Change Location for Project in messages
OSGeo/grass pull request #4193
Opened 2024-08-17 10:53 UTC by ecodiv

The startup message for first-time users refers to the old Locations. This should be changed to Projects to match the new naming used in 8.4+.

2024-08-17 11:59 UTC, echoix commented
@petrasovaa Did we settle on lowercase or uppercase project finally?

2024-08-17 13:09 UTC, echoix commented
There already has been a long discuss on this, we don't need to open it back. I just don't remember the conclusion

2024-08-17 14:36 UTC, veroandreo commented
> @petrasovaa Did we settle on lowercase or uppercase project finally?

Thanks Paulo @ecodiv ! We missed that one

We are using lowercase for "project" unless the word is the start of a sentence of course. And since you are at it please also use lowercase for mapset. Thanks! :raised_hands:

2024-08-17 15:10 UTC, ecodiv commented
> There already has been a long discuss on this, we don't need to open it back. I just don't remember the conclusion

OK, good to know for how to use it in tutorials.

2024-08-17 21:43 UTC, ecodiv commented
>  And since you are at it please also use lowercase for mapset. Thanks! 🙌

Done

2024-08-18 01:09 UTC, echoix requested changes
If we want lowercased project, the following would need to be adjusted

2024-08-18 01:09 UTC, echoix commented on gui/wxpython/datacatalog/infomanager.py
> +            (_("Create new Project"), onCreateLocationHandler),
```suggestion
            (_("Create new project"), onCreateLocationHandler),
```

2024-08-18 01:09 UTC, echoix commented on gui/wxpython/datacatalog/infomanager.py
> +            "which contain mapsets (subprojects). All data in one Project is "
```suggestion
            "GRASS GIS helps you organize your data using projects (locations) "
            "which contain mapsets (subprojects). All data in one project is "
```

2024-08-18 01:09 UTC, echoix commented on gui/wxpython/datacatalog/infomanager.py
> +            "You are currently in mapset PERMANENT in default Project {loc} "
```suggestion
            "You are currently in mapset PERMANENT in default project {loc} "
```

2024-08-18 01:09 UTC, echoix commented on gui/wxpython/datacatalog/infomanager.py
> +            "Consider creating a new Project with a CRS "
```suggestion
            "Consider creating a new project with a CRS "
```

2024-08-18 01:09 UTC, echoix commented on gui/wxpython/datacatalog/infomanager.py
> +            "Currently you are in its PERMANENT mapset which is used for "
```suggestion
            "You have successfully created a new project {loc}. "
            "Currently you are in its PERMANENT mapset which is used for "
```

2024-08-18 01:09 UTC, echoix commented on gui/wxpython/datacatalog/infomanager.py
> +            "clicking on the Project name.\n\n"
```suggestion
            "clicking on the project name.\n\n"
```

2024-08-18 01:09 UTC, echoix commented on gui/wxpython/datacatalog/infomanager.py
> +            "To continue, use Data Catalog below to switch to a different Project."
```suggestion
            "{string} GRASS GIS has started in a temporary project. "
            "To continue, use Data Catalog below to switch to a different project."
```

2024-08-18 01:09 UTC, echoix commented on gui/wxpython/datacatalog/infomanager.py
> +            "To continue, use Data Catalog below to switch to a different Project "
```suggestion
            "GRASS GIS has started in a temporary project. "
            "To continue, use Data Catalog below to switch to a different project "
```

2024-08-18 06:05 UTC, ecodiv commented
> If we want lowercased project, the following would need to be adjusted

Committed the suggested changes

2024-08-19 19:17 UTC, petrasovaa approved these changes

2024-08-20 22:34 UTC, echoix approved these changes

2024-08-20 22:34 UTC, merged