Checks: fix Flake8 F841 (local variable assigned to but never used) in python/grass/temporal
OSGeo/grass pull request #4200
Opened 2024-08-19 20:06 UTC by mshukuno

The following are fixes for Flake8 F841 (local variable assigned to but never used) in the python/grass/temporal directory.

In order to fix the F841 problem I deleted unused variable assignments, but I left the module declarations alone since the module itself assigns global or class variables. In this way, I was able to maintain the existing code structure while fixing the Flake8 issues. However, please check that any module declarations are unnecessary.

2024-08-20 16:30 UTC, echoix commented
@ninsbl Do you feel up to the challenge for the temporal module here?

2024-08-20 20:37 UTC, petrasovaa commented on python/grass/temporal/datetime_math.py
> +                return _("Time string seems to specify relative time")
I think this is enough:
```suggestion
            int(time_string)
            return _("Time string seems to specify relative time")
```

2024-08-22 20:03 UTC, petrasovaa requested changes

2024-08-22 20:03 UTC, petrasovaa commented on python/grass/temporal/temporal_raster_base_algebra.py
> +                        self.generate_map_name()
This looks like it could be removed, but `generate_map_name` actually modifies a dictionary, so I think we need to keep this as you have it.

2024-08-22 20:03 UTC, petrasovaa commented on python/grass/temporal/temporal_raster_base_algebra.py
> +                map_i.get_id()
can be removed

2024-08-22 20:17 UTC, petrasovaa commented
Also there should be updates in the flake8 configuration.

2024-08-23 17:17 UTC, petrasovaa approved these changes

2024-08-23 22:52 UTC, echoix approved these changes

2024-08-23 22:53 UTC, echoix commented
Seems right to me, approved by Anna too. Thanks again for your hard work @mshukuno !

2024-08-23 22:53 UTC, merged