checks: Flake8 F841 fixes in the wxpython directory part 2
OSGeo/grass pull request #4253
Opened 2024-08-29 18:29 UTC by mshukuno

## Description

Flake8 F841 (local variable assigned to but never used) fixes in the `gui/wxpython/dbmgr` directory. 

## Motivation and context

Changes require resolving a part of Flake8 warnings that are currently ignored. The issue title and number as follows.

- [Bug] Fix currently ignored Flake8 warnings [#1522](https://github.com/OSGeo/grass/issues/1522)

## How has this been tested?
The GUI worked fine when I briefly tested it.

## Types of changes

Removed unused variables and lines to fix F841.

- [X] Bug fix (non-breaking change which fixes an issue)
- [ ]  New feature (non-breaking change which adds functionality)
- [ ]  Breaking change (fix or feature that would cause existing
functionality to not work as before)

## Checklist
- [x]  PR title provides summary of the changes and starts with one of the [pre-defined prefixes](https://www.notion.so/utils/release.yml)
- [x]  My code follows the [code style](https://github.com/OSGeo/grass/blob/main/doc/development/style_guide.md) of this project.
- [ ]  My change requires a change to the documentation.
- [ ]  I have updated the documentation accordingly.
- [ ]  I have added tests to cover my changes.

2024-08-29 18:40 UTC, petrasovaa requested changes

2024-08-29 18:40 UTC, petrasovaa commented on gui/wxpython/dbmgr/base.py
> -            winCol = self.FindWindowById(idCol)
this can be removed

2024-08-29 18:40 UTC, petrasovaa commented on gui/wxpython/dbmgr/sqlbuilder.py
> -        ctype = self.dbInfo.GetTableDesc(self.dbInfo.GetTable(self.layer))[column][
It looks like this could be removed, together with couple lines before that.

2024-08-29 18:42 UTC, wenzeslaus requested changes

2024-08-29 18:42 UTC, wenzeslaus commented on gui/wxpython/dbmgr/base.py
> +            self.FindWindowById(idCol)
There are no side effects to the wxPython's [FindWindowById function](https://docs.wxpython.org/wx.functions.html#wx.FindWindowById), so there is no reason to call it when the return value is unused.

2024-08-30 15:52 UTC, petrasovaa approved these changes

2024-09-04 19:57 UTC, merged