v.generalize: Initialize all of structure contents before using it
OSGeo/grass pull request #4281
Opened 2024-09-05 21:38 UTC by ymdatta

Currently, in `head` which is a `POINT_LIST` structure, we are only initializing the next pointer to NULL, but data present in the point substructure is not initialized which implies that it would be filled with random data. To avoid such scenario, initialize point coordinates to zero.

This was found using cppcheck tool.

Additional information:

1. Machine used: Virtual Machine running Ubuntu 22.04.4 LTS.
2. Reproduction rate: 100%, reproducible every time.
3. Output from cppcheck prior to fix

<img width="842" alt="image" src="https://github.com/user-attachments/assets/ccdda3ca-90cb-4bfe-92f1-049f82152931">

After the fix

<img width="571" alt="image" src="https://github.com/user-attachments/assets/4528b134-f96b-4883-965c-86595692ef20">

2024-09-05 22:43 UTC, echoix commented
If this pattern is correct to merge, I'll approve and merge #4282, as it's the same reasoning

2024-09-09 22:42 UTC, nilason requested changes

2024-09-10 06:00 UTC, nilason approved these changes

2024-09-10 09:58 UTC, echoix approved these changes

2024-09-10 09:59 UTC, merged