wxGUI: Use r.mask.status to get info about mask
OSGeo/grass pull request #4519
Opened 2024-10-14 17:23 UTC by wenzeslaus

This replaces low level checks of MASK raster in the current mapset with calls of r.mask.status.

GConsole and SbMask require r.mask.status to output a potential name of the mask regerdless of mask being set or not, so this functionality still needs to be implemented first before moving this PR forward. History changes seem to be complete.

2024-10-31 13:11 UTC, wenzeslaus commented
Depends on #4531.

2024-12-31 17:40 UTC, echoix commented
> Depends on #4531.

#4531 was merged last month

2025-01-27 18:24 UTC, wenzeslaus commented
@lindakarlovska Feel free to review or comment here. I might be able to incorporate changes even after this is merged.

2025-01-28 16:31 UTC, petrasovaa requested changes

2025-01-28 16:31 UTC, petrasovaa commented on python/grass/grassdb/history.py
> +        "mask3d_name": mask3d_name,
A typo?

```suggestion
        "mask2d": mask2d_status["present"],
        "mask2d_name": mask2d_status["name"],
        "mask3d": mask3d_present,
        "mask3d_name": mask3d_name,
```

2025-01-29 14:29 UTC, wenzeslaus commented on python/grass/grassdb/history.py
> +        "mask3d_name": mask3d_name,
An oversight. I didn't know how to use `git diff --word-diff` together with `git add -p`. Now, I improved my setup:

```
sudo apt install git-delta
```

```
# ~/.gitconfig
[interactive]
    diffFilter = delta --color-only --features=interactive
```

2025-01-29 15:02 UTC, petrasovaa approved these changes

2025-01-29 15:38 UTC, merged

2025-01-30 13:37 UTC, lindakarlovska commented
That's a nice improvement. Just thinking about the sense of possible r3.mask.status module.

I am wondering how often users use 3D mask... or maybe more general, how many people work with 3D rasters in GRASS, do you have any idea @wenzeslaus ?

2025-01-31 13:22 UTC, wenzeslaus commented
Handling 3D rasters better would make sense. It's a kind of chicken and egg problem - more tools would lead to more usage, and more usage would lead to more tools. I was quite happy when I used them, but wished for more tools (and added some).