v.hull: Dereference after Null check
OSGeo/grass pull request #4524
Opened 2024-10-14 23:38 UTC by ShubhamDesai

This pull request addresses the issue identified by coverity scan (CID: 1207412)

- if (edges) is added before e = edges->next; and entering the loop to ensure that it is not NULL before accessing next member.
- before accessing the member e->delete check whether e is not NULL.
- while (e != edges && e != NULL); here added check e!=NULL to ensure that loop terminates as soon as e is NULL.

2024-10-15 13:03 UTC, metzm commented on vector/v.hull/chull.c
> +        } while (e != edges && e != NULL);
```suggestion
        } while (e != edges);
```
Same as above.

2024-10-15 18:19 UTC, ShubhamDesai commented
> If my understanding of the above is right, it should probably be enough to add a `if (!edges) return;` before `e = edges->next;`.

i guess using if (edges) will work the same 
because for !edges using return doesn't look good because function is void it may lead to additional warning in cppcheck i think.

2024-10-15 18:28 UTC, ShubhamDesai commented on vector/v.hull/chull.c
> +            if (e && e->delete) {
done

2024-10-15 18:28 UTC, ShubhamDesai commented on vector/v.hull/chull.c
> +        } while (e != edges && e != NULL);
done

2024-10-16 09:54 UTC, nilason commented
> > If my understanding of the above is right, it should probably be enough to add a `if (!edges) return;` before `e = edges->next;`.
> 
> i guess using if (edges) will work the same because for !edges using return doesn't look good because function is void it may lead to additional warning in cppcheck i think.

In effect they are the same. `return;` is perfectly valid and only way to return early in a void function (note: there is no return _value_). Let's compare them side by side:

```c
    if (edges) {
        e = edges->next;
        do {
            if (e->delete) {
                t = e;
                e = e->next;
                DELETE(edges, t);
            }
            else
                e = e->next;
        } while (e != edges);
    }
```

```c
    if (!edges)
        return;

    e = edges->next;
    do {
        if (e->delete) {
            t = e;
            e = e->next;
            DELETE(edges, t);
        }
        else
            e = e->next;
    } while (e != edges);
```

In my opinion the readability and intent of the code is much better with the latter (tip: search for "_early return_" pattern and "_pyramid of doom_" anti-pattern).

To the root cause of this issue. I managed to reproduce this with Clang's `scan-build`[^1], and it became more clear whence it originates. The macro `DELETE` may set `edges` to NULL if `edges == edges->next`:

https://github.com/OSGeo/grass/blob/241589424d9612b913ef7f5502839ee6ab2151bc/vector/v.hull/macros.h#L40-L43

We have the same problem with CleanFaces() and a similar one with CleanVertices() too.

@metzm I'm not quite sure of the implications if `edges == edges->next` and we exit the function early. Was everything that were supposed to be cleaned up, actually cleaned up to that point?


[^1]:  The analysis report is available here as a html bundle: [scan-build-2024-10-16-105627-63060-1.zip](https://github.com/user-attachments/files/17393244/scan-build-2024-10-16-105627-63060-1.zip)

2024-10-16 19:27 UTC, metzm approved these changes

2024-10-17 18:56 UTC, metzm commented
> We have the same problem with CleanFaces() and a similar one with CleanVertices() too.
indeed
> 
> @metzm I'm not quite sure of the implications if `edges == edges->next` and we exit the function early. Was everything that were supposed to be cleaned up, actually cleaned up to that point?

I think exiting the function early with
```
if (!edges)
        return;
```
is safe because there would be no edges left. `edges` is the root pointer to the double linked list, if it is NULL, the list is empty.

2024-10-19 16:23 UTC, echoix commented
@nilason Or others, if you are ok with Markus Metz's response and approval, let's merge this. On Monday I'll get it merged if everything is still fine

2024-10-19 18:41 UTC, nilason requested changes
Let us address CID: 1207410 and CID: 1207411 too, with this PR.

@metzm Thank you very much for your input!

2024-10-20 21:41 UTC, ShubhamDesai commented
> Let us address CID: 1207410 and CID: 1207411 too, with this PR.
> 
> @metzm Thank you very much for your input!

I did the changes.
also as you suggested @nilason i did the early return. I agree with you to exit early

2024-10-21 12:32 UTC, nilason approved these changes
@ShubhamDesai  Thanks!

2024-10-21 12:32 UTC, merged