docs: add intro text to imageryintro.html
OSGeo/grass pull request #4536
Opened 2024-10-16 09:47 UTC by neteler

This PR adds an overview text to `imagery/imageryintro.html` including a link to addons to not start this intro text without context.

(aside, addons URL fix in `g.gui.gmodeler.html`)

2024-10-16 11:44 UTC, nilason commented on imagery/imageryintro.html
> +are available as well.
```suggestion
GRASS GIS provides a powerful suite of tools for the processing and
analysis of geospatial raster data, including satellite imagery and
aerial photography. Its image processing capabilities encompass a broad
range of preprocessing operations, such as data import, georeferencing,
radiometric calibration and atmospheric correction. It is particularly
suited for handling Earth observation data, enabling the analysis of
multispectral and temporal datasets. GRASS GIS supports advanced
functionalities such as image classification, sensor fusion, and point
cloud statistics. The calculation of vegetation indices further enables
analyses of environmental, agricultural, and land cover dynamics. An
extensive collection of
<a href="https://grass.osgeo.org/grass8/manuals/addons/#i">addons</a>
further enhances its analytical capabilities.
```

2024-10-17 01:10 UTC, wenzeslaus requested changes
I also noticed that the words remote sensing are not mentioned. Too many terms to cover: EO, RS, image processing, imagery. I'm not sure what to suggest.

2024-10-17 01:10 UTC, wenzeslaus commented on imagery/imageryintro.html
> +further enhances its analytical capabilities.
Given you link to imagery:

```suggestion
further enhances its image processing capabilities.
```

2024-10-17 09:27 UTC, neteler commented on imagery/imageryintro.html
> +are available as well.
Thanks @nilason!

2024-10-17 09:56 UTC, nilason approved these changes
Great!

2024-10-17 10:05 UTC, neteler commented
> Too many terms to cover: EO, RS, image processing, imagery.

Attempt added in f578e6d.

2024-10-17 21:04 UTC, wenzeslaus approved these changes
Thanks!

2024-10-17 21:33 UTC, merged