docs: RFC on C++17 minimal standard support
OSGeo/grass pull request #4566
Opened 2024-10-21 11:51 UTC by nilason

Addresses  #4040.

For reference:
[GDAL RFC98](https://gdal.org/en/latest/development/rfc/rfc98_build_requirements_gdal_3_9.html)
[PDAL 2.4](https://github.com/PDAL/PDAL/releases/tag/2.4.0)
[GEOS#1144](https://github.com/libgeos/geos/pull/1144)

2024-10-21 11:57 UTC, echoix commented
Is there a way to write it such that the RFC doesn't have to be updated at each version? Such as the conditions that allow us to say: these are the supported ones without having to think more about it?

For Python, the case is quite easy.

2024-10-21 12:10 UTC, nilason commented
> Is there a way to write it such that the RFC doesn't have to be updated at each version? Such as the conditions that allow us to say: these are the supported ones without having to think more about it?
> 
> For Python, the case is quite easy.

I can only repeat what I said before on this matter: https://github.com/OSGeo/grass/issues/4040#issuecomment-2230309429.

2024-10-24 15:01 UTC, wenzeslaus commented
@echoix I would prefer the Python way as well, but I'm afraid @nilason is right that it is just more complicated for C and C++. Maybe it will change it in the future, but the nature of the ecosystem is just very different now.

One thing which we could do differently is updating the same RFC instead of creating a new one. I don't know if that's a good idea here or in general. For things like release schedule it seems to make sense, though.

2024-10-24 17:02 UTC, nilason commented
It is probable we will want to update C and C++ minimum standard only every 5–10 years,  so a new RFC weighing in all factors is not such a big deal I think. The current standard should be mentioned in doc/development/style_guide.md.

For reference eg. GDAL RFCs work in the same way, without "updating". Each RFC is a document in itself, with its history and adoption procedure.

2024-10-24 20:27 UTC, wenzeslaus commented
@nilason, do you want to make any changes to tested C and C++ version in relation to this? The gcc.yml workflow is already using `gnu17` and `c++17`, but perhaps adding new versions? I don't know what GCC is there, but the underlying image is currently `ubuntu-22.04`. Related to that, do you want to run the CI with clang? macOS seems like a good image to do that right now.

2024-10-24 20:29 UTC, wenzeslaus commented on doc/development/rfc/RFC10_cpp_language_standards_support.md
> +Moreover, important dependencies such as PDAL 2.4 (released in Mars 2022) and
```suggestion
Moreover, important dependencies such as PDAL 2.4 (released in March 2022) and
```

2024-10-24 20:29 UTC, wenzeslaus commented on doc/development/rfc/RFC10_cpp_language_standards_support.md
> +GEOS 3.14 do.
```suggestion
GEOS 3.14.
```

2024-10-24 20:38 UTC, wenzeslaus requested changes
I have some wording suggestions, but otherwise we are only testing C++17 in gcc.yml and our dependencies already require C++17, so I don't think there is much to discuss.

2024-10-24 20:38 UTC, wenzeslaus commented on doc/development/rfc/RFC10_cpp_language_standards_support.md
> +regarding C++ standard support.
```suggestion
Set a new minimum build requirement for C++ code to support the C++17 standard. This
supersedes the [RFC 7: Language Standards Support](language_standards_support.md) with respect to C++ standard support.
```

2024-10-24 20:38 UTC, wenzeslaus commented on doc/development/rfc/RFC10_cpp_language_standards_support.md
> +need or required it. Now, compilers with full C++17 support are available also
```suggestion
The RFC 7, which set the minimum supported C++ standard to C++11, was adopted 3.5
years ago. At that time, although the latest versions of common compilers had
full support for C++17, neither the GRASS GIS code itself nor its dependencies
needed or required it. Now, compilers with full C++17 support are available also
```

2024-10-25 22:51 UTC, nilason commented
> I have some wording suggestions, but otherwise we are only testing C++17 in gcc.yml and our dependencies already require C++17, so I don't think there is much to discuss.

Thanks for the good suggestions. In practice, also the mac runner is C++17, as that is the default with Clang 19.

2024-10-26 03:48 UTC, wenzeslaus approved these changes
If I recall correctly, the procedure is that the PSC needs to vote here by approving the PR. Please, check PSC mailing list for the last RFC voting.

I guess we could merge the draft and then only PSC-vote to "un-draft" it. I don't see much advantage in that.

2024-10-30 12:13 UTC, veroandreo approved these changes
Thanks @nilason!

2024-10-30 12:13 UTC, veroandreo commented on doc/development/rfc/RFC10_cpp_language_standards_support.md
> +code to the C++17 standard. This enables use of new C++17 features, if and when
```suggestion
code to the C++17 standard. This enables the use of new C++17 features, if and when
```

2024-10-30 12:13 UTC, veroandreo commented on doc/development/rfc/RFC10_cpp_language_standards_support.md
> +changes to current code. Continuous integration runners already compiles in
```suggestion
changes to current code. Continuous integration runners already compile in
```

2024-11-11 12:14 UTC, veroandreo submitted a review, later dismissed

2024-11-28 15:03 UTC, echoix commented
Since the motion was passed, it needs to be updated to no longer be a draft

2024-11-28 15:11 UTC, nilason commented
I updated and activated auto-merge.

2024-11-28 15:15 UTC, echoix approved these changes
Approving since adopted by the RFC

2024-11-28 17:13 UTC, merged