r.sim.water: add info to manual, add info about progress
OSGeo/grass pull request #4662
Opened 2024-11-06 21:39 UTC by metzm

* `r.sim.water` is a module with a number of important but not well documented parameters. This PR adds more information about some parameters to the manual.
 * It takes quite some time to run a simulation, another message is added to the progress of the simulation.

This PR tries to add info requested in https://github.com/OSGeo/grass/discussions/4475 to the manual

2024-11-06 21:49 UTC, petrasovaa commented on raster/r.sim/r.sim.water/r.sim.water.html
> + <tr><th>Landcover Category</th><th>Manning’s n value</th></tr>
```suggestion
 <tr><th>NLCD Landcover Category</th><th>Manning’s n value</th></tr>
```

2024-11-06 21:50 UTC, petrasovaa commented on raster/r.sim/r.sim.water/r.sim.water.html
> +<b>Manning's n for surface roughness</b><br>
```suggestion
<b>Suggested Manning's n for surface roughness</b><br>
```

2024-11-09 01:50 UTC, hmitaso commented
This sentence may be confusing  "The model is for shallow water flow, where "shallow" is defined by <b>hmax</b>"- Perhaps the paragraph could start with "the model tries to keep water "shallow" with maximum shallow water depth defined by hmax value (default is 0.3m). If hmax is reached then .... here goes the text that explains the increase in diffusion rate and related parameters .... The rest of the text that explains when these parameters may need to be adjusted sounds good to me.

2024-11-13 21:46 UTC, metzm commented
This new description comes from https://github.com/OSGeo/grass/discussions/4475, maybe @petrasovaa can clarify? I am not sure if the model tries to keep water "shallow". After `hmax` is reached, water flow can more easily overcome obstacles like sinks. "shallow" might [here](https://github.com/OSGeo/grass/discussions/4475) refer not to water depth, but to noise or sinks in the DEM used as input.

2024-11-14 18:09 UTC, metzm commented
@hmitaso New try to explain diffusion in order to keep water shallow and to overcome obstacles in https://github.com/OSGeo/grass/pull/4662/commits/ad725c7e65087f0c550971db3ed70603e1e3821d.

2025-01-06 21:10 UTC, neteler commented on raster/r.sim/r.sim.water/main.c
> +        _("A larger minimum tine step substancially reduces processing time, "
```suggestion
        _("Minimum time step for the simulation [seconds]");
    parm.mintimestep->description =
        _("A larger minimum time step substancially reduces processing time, "
```

2025-01-06 21:11 UTC, neteler commented on raster/r.sim/r.sim.water/main.c
> +        _("A larger minimum time step substancially reduces processing time, "
```suggestion
        _("Minimum time step for the simulation [seconds]");
    parm.mintimestep->description =
        _("A larger minimum time step substantially reduces processing time, "
```

2025-01-06 21:11 UTC, neteler commented on raster/r.sim/r.sim.water/main.c
> +        "Number of threads which will be used for parallel compute. Increasing "
```suggestion
        "Number of threads which will be used for parallel computation. Increasing "
```

2025-01-06 21:12 UTC, neteler commented on raster/r.sim/r.sim.water/r.sim.water.html
> +</pre></div>
```suggestion
The equations are

<div class="code"><pre>
dx = tan(slope) * cos(aspect)
</pre></div>

and

<div class="code"><pre>
dy = tan(slope) * sin(aspect)
</pre></div>
```

2025-01-06 21:12 UTC, neteler commented on raster/r.sim/r.sim.water/r.sim.water.html
> +natural sinks or river beds.Depending on the area of interest and the
```suggestion
natural sinks or river beds. Depending on the area of interest and the
```

2025-01-09 20:25 UTC, metzm commented on raster/r.sim/r.sim.water/main.c
> +        "Number of threads which will be used for parallel computation. Increasing "
Done with https://github.com/OSGeo/grass/pull/4662/commits/485a92305d067736a9b2a5d24be7731f87aeab21

2025-01-10 11:44 UTC, neteler approved these changes, later dismissed
Locally tested, looks good to me.

2025-01-10 18:24 UTC, neteler commented
May this be merged, @petrasovaa ?

2025-01-10 18:52 UTC, petrasovaa requested changes

2025-01-15 20:46 UTC, metzm commented on raster/r.sim/r.sim.sediment/main.c
> +          "Increasing the number of threads does not really speed up "
Done with https://github.com/OSGeo/grass/pull/4662/commits/bbf91175479a77b58d1a2109f3aee62c0460a48b

2025-01-15 20:46 UTC, metzm commented on raster/r.sim/r.sim.water/main.c
> +        _("Number of threads which will be used for parallel computation. "
Done with https://github.com/OSGeo/grass/pull/4662/commits/bbf91175479a77b58d1a2109f3aee62c0460a48b

2025-01-15 20:47 UTC, metzm commented on raster/r.sim/r.sim.water/main.c
> +    parm.mintimestep = G_define_option();
Done with https://github.com/OSGeo/grass/pull/4662/commits/bbf91175479a77b58d1a2109f3aee62c0460a48b

2025-01-15 21:48 UTC, petrasovaa commented on raster/r.sim/r.sim.sediment/main.c
> +          "Increasing the number of threads does not really speed up "
Could you elaborate on this? In your experience, there is no speedup at all? Because that's what the comment suggests. For sure it doesn't scale well, but at least for 4 threads the authors [report](https://doi.org/10.1016/j.cageo.2017.07.007) 3x speedup.

2025-01-21 16:57 UTC, metzm commented on raster/r.sim/r.sim.sediment/main.c
> +          "Increasing the number of threads does not really speed up "
I tried with up to 8 threads and observed a speedup of only max 5% despite all threads being fully used. This does not warrant such a waste of threads.

2025-01-30 14:33 UTC, neteler approved these changes
This is an important documentation fix, thanks.

2025-01-30 14:34 UTC, neteler approved these changes
This is an important documentation fix, thanks.

2025-01-30 15:05 UTC, neteler commented
> * `r.sim.water` is a module with a number of important but not well documented parameters. This PR adds more information about some parameters to the manual.

@petrasovaa since this documentation improvement is important, can we move on and merge this PR?

2025-01-30 21:35 UTC, petrasovaa approved these changes

2025-01-31 08:22 UTC, merged