r.cross: added testsuite for r.cross tool
OSGeo/grass pull request #4707
Opened 2024-11-16 04:19 UTC by Shreshth-Malik

Added Tests for `r.cross` Module

**Description:**

**Maps:** `map1` contains categories 1, 2, 3 (rows) and NULL; `map2` contains categories 1, 2 (columns) and NULL.
**Basic Test:** Verifies correct category generation, including combinations with NULL values.
**`-z` Flag Test:** Ensures exclusion of NULL values in cross-product categories.

2024-11-16 20:36 UTC, echoix commented
There are test failures on Windows https://github.com/OSGeo/grass/actions/runs/11867143742/job/33074831849?pr=4707#step:13:1741

2024-12-20 18:02 UTC, petrasovaa requested changes

2024-12-20 18:02 UTC, petrasovaa commented on raster/r.cross/testsuite/test_cross.py
> +        category_module = SimpleModule("r.category", map="crossed_map")
r.category has new option output_format=json, use that to avoid all the parsing

2025-02-22 19:02 UTC, Shreshth-Malik commented on raster/r.cross/testsuite/test_cross.py
> +        category_module = SimpleModule("r.category", map="crossed_map")
I tried incorporating output_format=json, but the program fails as GRASS is not recognizing as a parameter. Is there something like a GRASS Dev version i need to install or maybe another parameter that achieves the same?

2025-03-03 17:49 UTC, petrasovaa approved these changes

2025-03-03 17:50 UTC, merged