pygrass: Fixed E402 in vecto/
OSGeo/grass pull request #4715
Opened 2024-11-18 22:21 UTC by arohanajit

Since `libgis` needed to be imported first, I put the all the imports intitally menioned after libgis in a function which I subsequently called in order to resolve flake8

2024-11-19 02:23 UTC, petrasovaa requested changes
Use # noqa and please remove the extra file.

2024-11-19 02:39 UTC, echoix commented
If that extra file was a token used for something, you'd need to rotate it as it's now leaked.

2024-11-22 02:29 UTC, petrasovaa submitted a review, later dismissed

2024-12-10 13:03 UTC, echoix approved these changes

2024-12-19 12:47 UTC, echoix commented
@arohanajit could you take a look and solve the conflicts

2024-12-19 21:26 UTC, echoix approved these changes

2024-12-19 22:16 UTC, merged