r.out.vtk: replace dead WMS server with NASA GIBS WMS in docs (#4844)
OSGeo/grass pull request #4854
Opened 2024-12-17 09:47 UTC by rohannallamadge

This pull request updates the example in the ` r.out.vtk` documentation. The previous WMS server (http://wms.jpl.nasa.gov/wms.cgi) is no longer available, causing the example to fail.

**Changes made:**

Replaced the dead WMS server with NASA GIBS WMS (https://gibs.earthdata.nasa.gov/wms/epsg4326/best/wms.cgi).
Used the `BlueMarbleNG` layer for global imagery, which closely matches the original intent of the example.

2024-12-19 09:59 UTC, pesekon2 commented
When I try the new example, I get the following error:

```bash
> r.in.wms layers=BlueMarbleNG mapserver=https://gibs.earthdata.nasa.gov/wms/epsg4326/best/wms.cgi?       output=wms_BlueMarbleNG
ERROR: WMS server error: b'<?xml version=\'1.0\' encoding="UTF-8"
       standalone="no" ?>\n<!DOCTYPE ServiceExceptionReport SYSTEM
       "http://schemas.opengis.net/wms/1.1.1/exception_1_1_1.dtd">\n<ServiceExceptionReport
       version="1.1.1">\n<ServiceException
       code="LayerNotDefined">\nmsWMSLoadGetMapParams(): WMS server error.
       Invalid layer(s) given in the LAYERS parameter. A layer might be
       disabled for this request. Check wms/ows_enable_request
       settings.\n</ServiceException>\n</ServiceExceptionReport>\n'
```

2024-12-19 10:16 UTC, pesekon2 commented on raster/r.out.vtk/r.out.vtk.html
> +r.in.wms layers=BlueMarbleNG mapserver=https://gibs.earthdata.nasa.gov/wms/epsg4326/best/wms.cgi?
```suggestion
r.in.wms layers=BlueMarbleNG url=https://gibs.earthdata.nasa.gov/wms/epsg4326/best/wms.cgi? \
```

2024-12-19 10:19 UTC, pesekon2 commented on raster/r.out.vtk/r.out.vtk.html
> +r.in.wms layers=BlueMarbleNG mapserver=https://gibs.earthdata.nasa.gov/wms/epsg4326/best/wms.cgi?
Reasoning behind:

1) Missing `\` at the end of the line, making `sh` understand it as two one-line commands
2) Changing `mapserver` to `url` in `r.in.wms`. The change happened somewhere between GRASS 6 and GRASS 7 and it is a prehistoric remnant that should not be there for a long time, already.

2024-12-20 19:55 UTC, petrasovaa requested changes
Please remove unrelated changes from this PR

2024-12-20 21:59 UTC, pesekon2 commented
> Please remove unrelated changes from this PR

@rohannallamadge: They were introduced in [90ba339](https://github.com/OSGeo/grass/pull/4854/commits/90ba33975fe30595e35628f055455727ab2e9789) - it should be sufficient to revert the commit. As the changes were not there yesterday when I was making the review, I guess they slipped in together with your merge request.

2024-12-27 11:29 UTC, pesekon2 commented on raster/r.out.vtk/r.out.vtk.html
> +r.in.wms layers=BlueMarbleNG mapserver=https://gibs.earthdata.nasa.gov/wms/epsg4326/best/wms.cgi?
Fixed in 27412da89c99c712f71660d3c1fa653465844348

2024-12-27 11:30 UTC, pesekon2 commented
> When I try the new example, I get the following error:
> 
> ```shell
> > r.in.wms layers=BlueMarbleNG mapserver=https://gibs.earthdata.nasa.gov/wms/epsg4326/best/wms.cgi?       output=wms_BlueMarbleNG
> ERROR: WMS server error: b'<?xml version=\'1.0\' encoding="UTF-8"
>        standalone="no" ?>\n<!DOCTYPE ServiceExceptionReport SYSTEM
>        "http://schemas.opengis.net/wms/1.1.1/exception_1_1_1.dtd">\n<ServiceExceptionReport
>        version="1.1.1">\n<ServiceException
>        code="LayerNotDefined">\nmsWMSLoadGetMapParams(): WMS server error.
>        Invalid layer(s) given in the LAYERS parameter. A layer might be
>        disabled for this request. Check wms/ows_enable_request
>        settings.\n</ServiceException>\n</ServiceExceptionReport>\n'
> ```

Fixed in 27412da89c99c712f71660d3c1fa653465844348

2024-12-27 11:30 UTC, pesekon2 commented on raster/r.out.vtk/r.out.vtk.html
> +r.in.wms layers=BlueMarbleNG url=https://gibs.earthdata.nasa.gov/wms/epsg4326/best/wms.cgi? \
```suggestion
r.in.wms layers=BlueMarbleNG url=https://gibs.earthdata.nasa.gov/wms/epsg4326/best/wms.cgi? \
```

2024-12-27 12:06 UTC, pesekon2 commented on raster/r.out.vtk/r.out.vtk.html
> +r.in.wms layers=BlueMarbleNG url=https://gibs.earthdata.nasa.gov/wms/epsg4326/best/wms.cgi? \
```suggestion
r.in.wms layers=BlueMarble_NextGeneration url=https://gibs.earthdata.nasa.gov/wms/epsg4326/best/wms.cgi? \
```

2024-12-27 12:11 UTC, pesekon2 commented on raster/r.out.vtk/r.out.vtk.html
>  g.region n=4926990 s=4914840 w=591570 e=607800 res=30 -p
The computational region should be changed to follow the region and coordinate system of the WMS used. The same applies to the title -- it is not `Spearfish example with RGB data` anymore.

2024-12-29 10:18 UTC, pesekon2 commented
@rohannallamadge: What was the meaning of the last commit? It seems that the only effect is that the unrelated changes in python/grass/jupyter slipped again in in  781db51f210354f9951ee9f523496983337b9753

2024-12-29 10:28 UTC, rohannallamadge commented
sir @pesekon2 Apologies for the confusion regarding the last commit. The issue arose because my OneDrive integration caused unintended changes to be merged automatically into the `gh-phase` branch.

To resolve this and ensure a clean contribution, I have created a new branch `Mercator`  and submitted another PR with only the relevant changes.

2024-12-30 18:23 UTC, petrasovaa commented
Continued in #4897

2024-12-30 18:23 UTC, closed without merging