g.search.modules: add keyword=* for all modules
OSGeo/grass pull request #988
Opened 2020-09-24 14:29 UTC by AnikaBettge

Since the commit https://github.com/OSGeo/grass/commit/b339724848a8c881f636a4dca297cb7adfa29502 does not allow `keyword=""` with this change you can list all GRASS GIS modules with `keyword="*"`.

Developed with @griembauer.

2020-09-24 15:56 UTC, metzm requested changes
Using `keywords = ['']` is not safe because the behaviour of `str.find(sub)` is undefined for `sub = ''`. For example, `"mykey".find('')` should "Return the lowest index in the string where substring sub is found", but returns 0 which is technically wrong because `'m' != '\0'`.
Therefore I recommend to set keywords to `[]` or `None` and adjust `_search_module` such that it loops over keywords only if keywords are actually provided, otherwise simply return a list of all available modules.

2020-09-24 16:24 UTC, neteler commented
I'd recommend to add this (or similar) test case:
(putting here because of not knowing how to add it to the PR)
```

diff --git a/scripts/g.search.modules/testsuite/test_g_search_modules.py b/scripts/g.search.modules/testsuite/test_g_search_modules.py
index 512755bac..be6605a69 100644
--- a/scripts/g.search.modules/testsuite/test_g_search_modules.py
+++ b/scripts/g.search.modules/testsuite/test_g_search_modules.py
@@ -28,6 +28,13 @@ except ImportError:
 
 class TestSearchModule(TestCase):
 
+    def test_all_output(self):
+        module = SimpleModule('g.search.modules', flags="g")
+        self.assertModule(module)
+        stdout = decode(module.outputs.stdout).split()
+        # we expect at least 100 hits since we search for all modules
+        assert(len(stdout) > 100)
+
     def test_terminal_output(self):
         """ """
         module = SimpleModule('g.search.modules', keyword="water")
@@ -44,7 +51,7 @@ class TestSearchModule(TestCase):
         self.assertEqual(stdout[3]['name'], 'r.water.outlet', 'r.water.outlet')
         self.assertTrue('keywords' in stdout[3]['attributes'])
 
-    def test_shell_outout(self):
+    def test_shell_output(self):
         module = SimpleModule('g.search.modules', keyword="water", flags="g")
         self.assertModule(module)
         stdout = decode(module.outputs.stdout).split()
```

2020-09-24 18:07 UTC, metzm commented
This is not a bug fix because `g.search.modules keywords=""` does not provide keywords even though they are required, and relies on the undefined behaviour of `str.find('')`. The labels for this PR should be changed accordingly.

2020-09-25 06:57 UTC, neteler commented
Replaced by ##989

2020-09-25 06:57 UTC, closed without merging